### ISSUE TITLE
eroare subtitrari

### ISSUE THREAD

**Issue by bbox1** [xngsrs/myhobby#1]
Salut!
Am gasit o eroare in plugin-urile de subtitrari.
De exemplu in addonul ptr. subs.ro, linia 84 din service.py:
in loc de: **urllib.quote_plus(dirfile)** trebuie: **urllib.quote_plus(ofile)**
La fel si ptr. subtitrarinoiro si titrariro
bbox

**Comment by xngsrs** [comment]
Salut,
o sa fac modificarea la urmatorul update. Multumesc!

**Comment by xngsrs** [comment]
Reparat in 1886381
