### ISSUE TITLE
Zfilmeonline ropack

### ISSUE THREAD

**Issue by visinel** [xngsrs/myhobby#10]
Salut ,addonul din ropack zfilmeonline nu functioneaza ,si a schimbat adresa in : www.filmeonline.bz
Multumesc

**Comment by xngsrs** [comment]
Salut, am rezolvat, multumesc

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
