### ISSUE TITLE
Câteva idei

### ISSUE THREAD

**Issue by Drakses** [xngsrs/myhobby#18]
Salut,
Aș avea câteva puncte/sugestii de adresat în versiuni viitoare:
- Posibilitatea de a folosii view types în plugin.
Mă gândesc că tine de definirea categoriilor/subcategoriilor:
Addons>Movies
Addons>TV shows>Seasons>Episodes
etc.
- Folders de sezoane pentru emisiunile TV, Seriale (ex. În ClickSud toate episoadele din toate sezoanele sunt în același loc) 
- Asta tine de ClickSud, nu știu dacă este și în ceilalți scrapers. Episoadele sunt de tip folder ce conține linkuri de streaming. Cred că din acest motiv nu le putem marca cu seen check mark. Este posibil să le implementam actions/links? Click episod>pull dialog box cu stream providers? Este greu să ții minte ce ai văzut și ce nu. Sau dacă nu este posibil, măcar implmetat cum sunt favoritele, când mark ca văzut sa apară un "x -" la începutul numelui cum apare "fav -". 
- Posibilitatea de a rula în background query-ul făcut de addon. 

Orice dacă poți implementa din punctele de mai sus aș fii foarte recunoscător. Îți mulțumesc pentru munca depusă și dacă ai un cont de donații hit me up cu un link. 

Stimă.

**Comment by xngsrs** [comment]
Salut,
o sa am gandesc la imbunatatirile propuse. 

- View-types se poate, nu m-am mai gandit la asta de cand am facut addonul pentru ca eu folosesc numai list.

- E posibil sa fie anumite probleme in legatura cu marcarea ca vizionat, din cauza ca unele link-uri au diferite nume la fiecare accesare, dar teoretic ceva ar trebui sa se poata face. Addonul meu nu functioneaza ca celelalte care iau filmele din liste prestabilite, ia filmele asa cum apar pe site-urile incluse, de aici si problemele cu marcatul ca vizionat, pe care am preferat sa il fac "in house"

- Rulatul in background nu mi se pare o idee prea buna, pentru ca eu vreau sa stiu daca nu cumva mi s-a parut ca am apasat pe butonul telecomenzii sau chiar am apasat, plus ca vreau sa am un control, poate o sa fac o setare pentru asta.

P.S. nu fac asta pentru bani, ca altii (nici macar pentru donatii), o fac doar pentru ca eu folosesc ;)

**Comment by xngsrs** [comment]
Am bagat setare pentru partea de query, vezi la setari in addon dupa ce faci actualizarea, am activat view types pentru filme, poti sa iti selectezi ce view vrei. Am rezolvat si cu marcarea ca vizionat in clicksud.
chestia cu "Click episod>pull dialog box cu stream providers" nu o sa se intample, site-urile romanesti sunt foarte diferite si nu se poate marca la toate folderul ca vizionat, pentru ca multe au in acelasi foder mai multe episoade cu tot cu surse. 
Daca apar erori pe care nu le-am vazut eu, poate mai deschizi un issue ;)
