### ISSUE TITLE
Romanian Pack error

### ISSUE THREAD

**Issue by ursan2003** [xngsrs/myhobby#2]
Salut
am o problema cu Romanian Sites Pack pe android cu kodi 16.xx
pe windows merge snur
problema a aparut dupa un update la addon cam acu vreo 10 zile ,inainte de acel update era ok
logul arata asta
21:34:59 T:1968012936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: unqualified exec is not allowed in function 'parse_menu' it contains a nested function with free variables (filmeonlineto.py, line 198)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.romanianpack/default.py", line 17, in <module>
                                                core.sectionMenu()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.romanianpack/resources/Core.py", line 83, in sectionMenu
                                                imp = getattr(__import__(site), site)
                                            SyntaxError: unqualified exec is not allowed in function 'parse_menu' it contains a nested function with free variables (filmeonlineto.py, line 198)
                                            -->End of Python script error report<--
21:34:59 T:1742549248   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.romanianpack/
21:34:59 T:1742549248   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.romanianpack/) failed
Am facut downgrade la versiunea 1.28 si merge
Multumesc anticipat

**Comment by xngsrs** [comment]
Salut, o sa ma uit sa vad despre ce e vorba

**Comment by xngsrs** [comment]
Rezolvat in 07cf9f51

**Comment by ursan2003** [comment]
Sa rezolvat puternice,mii de multumiri pentru munca depusa
