### ISSUE TITLE
Feedback pentru versiunea 1.0.48

### ISSUE THREAD

**Issue by Drakses** [xngsrs/myhobby#20]
Salut,

Revin cu drag. Query în background merge as intended, multumesc. View types merg și ele, dar mă gândeam dacă am putea să îi dam un id separat fiecărui context (parent>child>child) pentru a putea aplica view types diferite fiecărei categorii/subcategorii. Nu este ceva foarte important, doar dacă se poate și ai dispoziție.

Și acum adevăratele motive pentru care am deschis issue.
1. In clicksud, 'Seriale românești' și 'Emisiuni online' nu mai pot fii accesate. Loading-ul se termina în eroare.
2. Providerul Hqq.tv se termină tot timpul în eroarea că nu a găsit niciun obiect JSON pentru a fi dectiptat. Se întâmplă indiferent de site, film etc.

Mulțumesc încă o dată pentru efortul depus. :)

**Comment by xngsrs** [comment]
Salut,
am rezolvat clicksud, mai are cateva "bubite" dar nu pot face mai mult de atat, site-ul e cam haotic.
Hqq nu se poate rezolva deocamdata. Desi nu tine de mine, e alt addon care face asta, am incercat, asa cum incearca si altii inca.
View types pe categorii nu se poate face, am stabilit deja ca addonul meu nu functioneaza dupa liste prestabilite (cum sunt altele), prin urmare nu prea exista categorii, toate sunt preluate de pe site-urile in cauza.
Daca mai gasesti alte bube, astept issue ;)

**Comment by marieryro** [comment]
Salut , din ultimele conversații mi ai zis sa scriu aici. Nu gasesc însă unde sa deschid un nou top. De ceva vreme in MRSP  Despreseriale nu mai merge. Poti face ceva? Multumesc anticipat

**Comment by xngsrs** [comment]
Salut, o sa il repar.
Ar trebui sa deschizi un issue, ai avut noroc ca am vazut mailul.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
