### ISSUE TITLE
Fs online nu merge

### ISSUE THREAD

**Issue by maxbaxter** [xngsrs/myhobby#22]
Salut!Felicitari pentru add on chiar e ceea ce trebuie facand comparatie cu alte add onuri internationale.Informare:FS online nu mai are niciun player functional de cand s au inchis openload si rapidvideo.Vidoza si mixdrop nu merg.

**Comment by xngsrs** [comment]
Salut!
MRSP arata link-ruile suportate de un addon dependinta, numit URLResolver, deci din punctul de vedere al MRSP, functioneaza.
**Ca sa nu te las totusi pe dinafara, am reparat eu mixdrop si am mai adaugat si videomega.** Pentru vidoza mai trebuie asteptat.
Incearca sa folosesti si torrentii din MRSP, functioneaza foarte ok, daca ai posibilitatea si iti permite hardware-ul.

P.S. pentru mixdrop si videomega nu va fi incarcata automat subtitrarea, deci va trebui sa alegi una, folosind unul din addonurile de subtitrari din depozitul meu.

**Comment by maxbaxter** [comment]
Multumesc frumos!
