### ISSUE TITLE
torrent2http - windows 10 x64 error

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#25]
Salut.
Am o problema pe windows 10 x64 la MRSP si Torrenter. Nu vrea sa mearga nicicum cu torrent2http.
Nici daca in MRSP la ”Actiune la click” aleg ”Play cu MRSP (torrent2http) si nici daca aleg ”browse” sau ”play cu torrenter” si in torrenter la setari aleg ”Torrent2http (libtorrent via http)”. Pe un Vero 4k cu OSMC, merg aceste setari fara probleme.
Initial nu a vrut sa plece nici python-libtorrent dar am dat de [un post pe net si am rezolvat cu libtorrent](https://github.com/DiMartinoXBMC/script.module.libtorrent/issues/14#issuecomment-606251549), dar apoi am dar de necaz cu Torrent2HTTP. Inclin sa cred ca iti e cunoscuta problema. E ceva cu BINul de x64 care lipseste. Am gasit ceva pe github, dar nu am reusit sa rezolv. Poate arunci un ochi [**aici**](https://github.com/markop159/KODI-Popcorn-Time/tree/master/plugin.video.kodipopcorntime/resources/bin/windows_x64) si [**aici**](https://github.com/markop159/KODI-Popcorn-Time/issues/102). Sper sa poti rezolva ceva.
Atasez si un Kodi log
[kodi.log](https://github.com/xngsrs/myhobby/files/4411839/kodi.log)

Multumesc pentru tot ce faci si pentru addonul acesta super bun.

**Comment by xngsrs** [comment]
Salut, 
o sa rezolv in curand, mutumesc pentru sesizare.

**Comment by xngsrs** [comment]
am facut un update [la torrent2http](https://github.com/xngsrs/myhobby/commit/8c1d77979f3eda6ec606d3cfa4160ca837af0d6a), incearca si vezi daca merge acum, din pacate inca nu am cum sa testez pe windows deocamdata.
Daca nu merge nici acum, te rog sa atasezi iar noul log.
Daca merge, poti inchide sesizarea sau o inchid eu mai tarziu. Mersi!

**Comment by angelitto2005** [comment]
Nu merge. In torrenter e pus pe torrent2http. In MRSP am testat cu ”Play cu MRSP” si ”Browse cu Torrenter”. Eroare la amandoua. Versiunea de torrent2http, e 029a.
[kodi.log](https://github.com/xngsrs/myhobby/files/4415041/kodi.log)

**Comment by xngsrs** [comment]
Daca mai poti sa faci un test si gata, am facut un update la [0.2.9b](https://github.com/xngsrs/myhobby/commit/fe560f71d76a469c573a7ddbc1733ad452739fc1).
Daca nu merge nici acum, o sa fac rost de ceva cu windows sa testez eu.
Sa ma anunti totusi, daca o ia. Mersi!

**Comment by angelitto2005** [comment]
Merge perfect acum. Si cu MRSP si cu Torrenter. Ai reusit. Multumesc frumos.

**Comment by xngsrs** [comment]
Daca reusesc sa fac o masina virtuala cu windows pe care sa mearga kodi, o sa incerc sa vad si care e treaba cu libtorrent. Deocamdata mrsp player nu are nevoie de python-libtorrent.
