### ISSUE TITLE
Implementare MRSP in Meniu Kodi

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#26]
Salut.
Revin cu o intrebare si cu niste buguri. Sper sa nu te stresez :)
O sa deschid issues separate sa nu le incurcam, caci is mai multe.

Am importat in Kodi prin Exodus (nu am gasit alta modalitate mai buna) libraria mea de TV Shows din Trakt. Intrebarea este daca ai putea implementa o setare in Kodi, cand dau click dreapta pe episodul unui serial din sectiunea ”TV Shows” sa apara optiunea Search(sau play) with MRSP. Ceva gen cum e optiunea de la Metalliq. Momentan, la normal click, porneste cu Exodus, caci prin el am importat libraria, dar prefer sa ma uit de pe torrente caci e calitatea mai buna.
Atasez si o poza sa iti faci mai bine o idee. 
https://postimg.cc/KK93xypp

Aceasta optiune ar fi binevenita caci daca vrem sa vizionam un episod al unui serial, dam la TV Shows si imediat il putem cauta si reda de la right click. Acum cateva luni, la click dreapta alegeam Metalliq4Qed si el imi dadea o lista cu playere. Iar de acolo alegeam Torrenter si in el aveam activat searcherul filelist. Dar acum nu mai merge caci searcherul respectiv nu mai e actualizat si trebuie de fiecare data sa caut manual episodul in MRSP. 
Asa ca ar fii super daca ai putea implementa in acel meniu sa putem da ”search” sau ”Play cu MRSP” la seriale.
E doar o idee pentru viitoare update-uri.

**Comment by xngsrs** [comment]
E bine ca ai pus sesizari separate :)
Nu stiu sigur cum functioneaza chestia asta cu adaugatul de meniu din alt addon in alt addon, mai facusem chestii din astea dar in alte versiuni de kodi si am uitat deja. O sa ma interesez. Daca mi se pare simplu si pot face, o sa bag ceva in setari pentru a afisa meniul de care zici. Daca nu...mai ai de asteptat :)

P.S. 
Mi se pare ca te complici cam mult cu fel si fel de addonuri, ca sa faci cu ele ce poti face cu unul singur: sa vezi filme si seriale. 
De aia m-am apucat sa fac MRSP, ca sa am un addon exact asa cum voiam eu sa fie, sa folosesc unul singur din care sa vad orice vreau, asa cum vreau. In timp am tot adaugat optiuni, in functie de ce am crezut eu ca imi trebuie. 
Singura chestie pe care nu o pot face e integrarea in libraria kodi, pentru ca eu nu iau filmele si serialele ca altii, din aceeasi sursa, adica trakt. Eu le iau asa cum apar, direct de pe site-uri.

**Comment by angelitto2005** [comment]
Sincer, chiar nu am multe addonuri. Si alea care le am nici nu le folosesc la filme. De ex. am Exodus ca sa imi faca sync la serialele ce le adaug in Trakt (de pe pc) si sa-mi apara in Kodi. Si sa pot vedea listele din Trakt. Doar pentru asta il tin. Apoi am Numbers, doar de forma, caci nu il folosesc. Am Youtube, care imi place caci mai pun muzica seara prin Receiver si sistemul 5.1. Am Torrenter care impreuna cu  filelist era baza, in trecut. Iar acum baza e MRSP(pentru torrente). Daca ai remediat chestia cu ”Vazute”, atunci e aproape perfect acest addon. Apoi mai e [OpenMeta ](https://github.com/a4k-openproject/plugin.video.openmeta)si [OpenInfo](https://github.com/a4k-openproject/script.extendedinfo). Cred ca ai auzit de ele. [Repository aici](https://github.com/a4k-openproject/repository.openmeta).
Am o idee cum sa faci implementarea in meniu la Kodi. OpenMeta e un forked la Metalliq. Iar OpenInfo (Extendedinfo) chiar e util. iti arata informatii despre filme si seriale, actori, etc. Chiar il folosesc mult.
Ce voiam sa zic cu astea. OpenMeta nu e player ci el iti recunoaste toate playerele instalate in Kodi si daca dai click dreapta pe un stream din librarie si alegi OpenMeta, poti rula acel film cu unul din playerele instalate in Kodi.
Vezi pozele de mai jos.
https://postimg.cc/R32XfqzH
https://postimg.cc/xkX6cMBQ
In felul acesta, nu mai trebuie sa intru in fiecare addon, ci direct din librarie pot vedea orice episod. E mult mai simplu asa decat sa intru in fiecare addon si sa caut filmul. Si merg si din OpenInfo. Tot asa se deschid playerele instalate in Kodi. Problema este ca MRSP nu e recunoscut ca player. Desi nu ma pricep prea bine, totusi am vazut ca e nevoie de un fisier json, astfel incat OpenMeta datorita acelui fisier sa-l recunoasca pe MRSP ca player.
In OpenMeta, la ”setari/import players from web” este acest link:
http://bit.ly/openplayers
sunt cateva dar in linkul de mai jos sunt mai multe si eu de aici le-am importat. E din cellardoortvrepo.
http://cellardoortv.com/metalliq/players/
Am incercat dupa import sa modific fisierul json de Torrenter si sa pun datele din MRSP dar nu a mers. Acum am gasit pe net si o pagina cu [json.openplayers](https://github.com/a4k-openproject/json.openplayers). Poate te ajuta.
Poate e greu de implementat, sau poate e o chestie simpla pentru tine. Nu stiu, dar sper sa reusesti. Ar fi super sa putem da play direct din librarie fara sa mai intram prin toate addonurile.
Am scris cam mult, dar am vrut sa fiu cat mai explicit :)

**Comment by xngsrs** [comment]
Cu openmeta nu ma bag, a mai vrut un utilizator asa ceva, dar nu am chef sa stau sa creez un fisier inutil pentru mine, care nu are legatura cu niciun addon de-al meu. 
Pentru meniu ramane sa ma documentez, cand am timp.

**Comment by angelitto2005** [comment]
Inteleg. Daca poti sa implementezi in meniul contextual din Kodi, la ”play using” sa dea ”play sau search cu MRSP”, ar fi binevenita aceasta imbunatatire. Cred ca te poti inspira si de aici:
https://kodi.wiki/view/Context_Item_Add-ons
https://forum.kodi.tv/showthread.php?tid=326256

Daca insa nu reusesti si totusi iei in considerare sa creezi un Meta player pentru MRSP, iti las un link unde poti afla ce si cum:
https://github.com/roee88/meta4kodi/wiki/Writing-a-Meta-player

Cred ca pentru tine e joaca sa faci un astfel de meta.json, dar pentru mine sunt limbi straine :)

Oricum, orice decizie vei lua, iti multumesc. Si iti multumesc si pentru rabdarea ta si pentru bugurile care le-ai raparat deja. Acest addon si subtitrarile cred ca sunt printre cele mai apreciate de romanii care folosesc Kodi.

**Comment by audiosistem** [comment]
Salut!Am intrat in mare parte...sa-ti cer...dar,
![Ptr MRSP](https://user-images.githubusercontent.com/6246768/78469456-2b7a7980-772a-11ea-969c-908b5cfbc772.jpg)
a facut-o angelitto2005 inainte.Daca este complicat(sunt un amator)nu este o problema,eu unul iti multumesc,pentru ce faci.

**Comment by xngsrs** [comment]
@audiosistem nu promit, o sa vedem, cand am timp, dupa ce mai rezolv din bug-urile care tot apar.

**Comment by audiosistem** [comment]
Multumesc!I-am scris(nestiind daca tine doar de tine) si lui a4k-openproject.O zi buna!

**Comment by xngsrs** [comment]
Am facut [ceva](https://github.com/xngsrs/myhobby/commit/fad515fcb0a3a66152ae547538e3f4634faf1917), am adaugat context global, pe langa alte modificari "minore", sper ca asa voiati. Dupa parerea mea, nu cred ca mai e nevoie de fisier openmeta player. 
Verificati cand aveti chef si anuntati-ma.

**Comment by angelitto2005** [comment]
Wow. Asa repede ... nu pot sa cred. Esti incredibil. Da, asa ceva voiam.  Si cu aceasta modificare, nu prea mai e nevoie de OpenMeta. Cel putin pentru mine.
Dar mai am o mica rugaminte. La filme, e totul ok, le gaseste si pe cele freeleech si pe cele normale. dar la seriale gaseste doar episoade individuale. E posibil ca la search in loc de ”Arrow.s01.e01”, sa caute si ”Arrow.s01”? In felul acesta apar si torentii cu tot sezonul 1 din Arrow. Si, cel mai important, apar si cei freelech.
Asta e setarea pe care o voiam de la inceput si din cauza ei deschis aceasta sesizare :)
Crezi ca e posibil?

**Comment by audiosistem** [comment]
Chapeau bas!Nu stiu ce ai schimbat,dar la mine...cu parere de rau,a stricat.Actualiza greoaie la 1.0.75,din widget 1 a disparut FilmeOnline2016-Recente si nici nu a aparut in search la OpenMeta.Am facut un jpg.cum mi-as dori,daca e foarte complicat,necesita si implicare a4k-openprojec...te rog sa ma scuzi!Multumesc,mult pentru ce faci!O zi buna!
![Ptr MRSP](https://user-images.githubusercontent.com/6246768/78500671-98a90180-7760-11ea-9141-e028750417a5.jpg)

**Comment by xngsrs** [comment]
@angelitto2005 Pot sa bag o setare in Misc, de genul: "Mod cautare trakt si context": "Edit box sau Direct", pe edit box iti apare caseta cu keyboard completata deja, din care tu poti sa stergi ce vrei, iar pe direct sa caute ca pana acum.
@audiosistem 
filmeonline2016 a disparut de pe web. Daca ii gasesti adresa ( testezi pe pc sau browser) il pot reface, altfel pot doar sa il sterg. Si ca sa iti explic: eu nu stric disponibilitatea filmelor din MRSP, eu repar. Daca site-urile respective isi schimba adresa, codul sau continutul, nu e din vina mea.
Referitor la meniul tau de acolo, observ ca pe tine nu te ajuta meniul de context, deci iti trebuie fisier openmeta.

@all
Daca o sa am timp si mai ales tragerea de inima sa fac un fisier pentru openmeta, acesta nu va avea cum sa fie integrat oricum in MRSP, in mod normal userii isi fac ei acel fisier, daca vor si pot, pentru ca nu depinde de MRSP, ci de alt addon

**Comment by angelitto2005** [comment]
Daca cu acea setare apar torentele cu sezoanele serialelor, e perfect. E usor sa schimbam ”direct” sau ”edit box” din setari. Totusi abia dupa ce o testez imi pot da cu parerea.

**Comment by audiosistem** [comment]
Departe de mine,orice gand a jigni.Cu scuzele de rigoare ca,n-am verificat FilmeOnline anterior.Inca o data scuze.

**Comment by xngsrs** [comment]
@angelitto2005 Pe "edit box" va fi exact cum este in MRSP meniul de "caută variante"
@audiosistem nu imi place ca sunt multi din categoria celor care zic ca update-urile strica, cand de fapt nu e asa. Ca se mai fac niste greseli minore care se repara ulterior, e una, dar actualizarile nu strica, ci imbunatatesc. Ai oricum versiunea anterioara de MRSP, daca doresti sa testezi, ca poate nu ma crezi: [plugin.video.romanianpack-1.0.74.zip](https://github.com/xngsrs/myhobby/files/4434043/plugin.video.romanianpack-1.0.74.zip)

**Comment by audiosistem** [comment]
Multumesc!

**Comment by angelitto2005** [comment]
Da, am inteles acum. La ”edit box”, va apare casuta de dialog si eu sterg doar e01. E bine si asa 👍

**Comment by angelitto2005** [comment]
@audiosistem, ai rabdare. Sunt sigur ca daca va avea timp, va face si un metaplayer. Eu am reusit sa fac cateva de test si le vede OpenMeta, dar nu merg. Parametrii de search din acel fisier sunt problema.
Dar daca iti merge din meniu: Play with MRSP”, eu zic ca e mai ok si mai bine asa, pentru ca OpenMeta nu cred ca mai e intretinut si daca apare vreo eroare, nu iti mai merge meniul contextual. dar ”Play with MRSP”, nu depinde de openmeta si e mai sigur ca nu vor fii probleme in viitor.
Parerea mea.

**Comment by audiosistem** [comment]
Last edit:Pe telefon,xiaomi note(nu stiu daca este relevant),unde n-am updatat...Filmeonline 2016...merge Miami Bici.Daca ajuta.

**Comment by xngsrs** [comment]
@audiosistem nu este din cauza actualizarii...pe mine nu ma ajuta cu nimic, acum site-ul este online. Daca actualizezi acum, o sa fie exact acelasi lucru, daca merge site-ul online merge si in MRSP, daca nu...nu

**Comment by xngsrs** [comment]
@angelitto2005  am [bagat](https://github.com/xngsrs/myhobby/commit/714962e411b627e17b8d85945a5fe7032b795787) setare in Misc. Am adaugat totusi 3 variante, edit box, direct1 - cautare directa cu sezon si episod, direct2 - cautare directa doar cu sezon.
