### ISSUE TITLE
Bug MRSP - Vazute

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#27]
Daca prima varianta (search sau play cu MRSP in meniu Kodi) nu e posibil de implementat, atunci cred ca am gasit o alta varianta dar e buguita. In MRSP, Sectiunea ”Vazute”, nu functioneaza corect. Cred ca scopul ei  e sa poti relua de acolo vizionarea episoadelor in continuare. Daca de ex. aleg un torrent cu Sezonul 2 al unui serial si vad primele 2 episoade, daca dau la ”Vazute” si aleg din nou ep.2 ar trebui sa-mi apara toate episoadele sezonului din acel torrent si sa pot alege ep.3. Corect? 
Nu am incercat sa folosesc aceasta optiune pana azi si vad ca imi da eroare. Si pe windows 10 si pe OSMC. 
Am pus si un log de pe win10.
[kodi_vazute.log](https://github.com/xngsrs/myhobby/files/4421449/kodi_vazute.log)

Poate se poate face ceva in acest caz.

**Comment by xngsrs** [comment]
Aici se poate lucra, se poate face sa functioneze si asa, desi nu asta a fost intentia mea. Nu am vrut sa reiau ce am vazut, am vrut doar sa stiu ce am vazut, mai nou si cand, de aia am adaugat si data vizionarii. 
Chestia asta apare la ce vezi din exterior si la torrentii care au mai multe fisiere video in ele, stiu despre ce e vorba, o sa o rezolv.

**Comment by angelitto2005** [comment]
Vad ca la ”Play cu MRSP” ai rezolvat deja. Pot sa reiau de unde am ramas. Super.
Daca poti si la restul, e ok, daca nu, e bine si asa 👍

**Comment by xngsrs** [comment]
Pai, daca e ok acum, atunci se poate inchide sesizarea asta, nu?
