### ISSUE TITLE
Bug Torrenter - stergere fisiere

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#28]
Am mai gasit o varianta pentru ”Warched History”, dar merge corect doar pe Windows 10. Pe OSMC (eu acolo vizionez seara filmele, direct pe TV) are un bug. Folosesc combinatia urmatoare. Actiune la click: ”play cu torrenter”. In felul acesta, daca caut un torrent (un sezon al unui serial) cu MRSP si ii dau play la un episod, in urmatoarea seara, doar deschid Torrenter si dau la ”Wached History”. Iar acolo imi apar toate episoadele vizionate din acel sezon. Iar daca dau pe unul din ele, se deschide torentul cu toate episoadele sezonului si pot alege episodul ce doresc sa-l urmaresc in continuare. Ei, pe win10 totul e ok, dar pe OSMC, dupa ce dau ”stop”, nu se sterg episoadele downloadate pe microSD card. Inainte, cand foloseam torenter+filelistro, se stergeau. Pe win10, vad ca se sterg, dar pe OSMC, nu.  Trebuie sa intru de fiecare data sa le sterg manual ca se aduna.  Folosesc doar freeleech deci nu le tin la seed.
La torrenter am setat asa:
Keep dowloaded files=delete
Predownload and play next episode=on
Autoplay next episode (or ask)=off, asta ca sa ma intrebe daca vreau pe urmatorul sau nu.

Insa, daca in MRSP aleg: Browse cu torrenter sau ”Play cu MRSP”, se sterg, dar nu mai imi apar in Torrenter la ”Watched History” si trebuie sa caut episoadele de fiecare data, manual in MRSP(caci nu merge sectiunea Vazute). E ca un lant. Se leaga una de alta :)
Atasez si aici un log din OSMC
[Kodi osmc.log](https://github.com/xngsrs/myhobby/files/4421471/Kodi.osmc.log)

Ar fii super daca ai putea rezolva macar una din aceste 3 issues.
Multumesc.

**Comment by xngsrs** [comment]
Nu prea ma mai ocup de torrenter, de aia mi-am facut propriul player in addon, e mai simplu pentru mine, dar si pentru altii. 
Nu stiu, poti sa incerci sa instalezi versiunea mai veche de torrenter, pe care probabil ca o gasesti tot in repo la mine.
De investigat..oricum...cand o sa am timp, ca se pare ca stau baietii mult pe acasa si tot modifica la site-uri in continuu :))

**Comment by angelitto2005** [comment]
Am facut niste teste in OSMC asa cum mi-ai zis. Am instalat o versiune mai veche, tot de la tine din repo (2.6.6b) dar la fel, nu stergea episodul dupa ce il vizionam. Asa ca am instalat iar v.2.7.6 si cand s-a terminat episodul, nu s-a sters si mi-a dat eroare. Asa ca am luat logul.
[kodi torrenter crash.log](https://github.com/xngsrs/myhobby/files/4431892/kodi.torrenter.crash.log)
In MRSP e ”Play cu Torrenter” si in Torrenter era setat ”torrent2http”.
Apoi in Torrenter am testat setarea ”pyrrent2http” si se pare ca asa e totul ok. Se sterg episoadele vizionate.
Oricum, acum e bine. Am 2 variante care functioneaza perfect cu Watched history. 

- Play cu MRSP + Vazute
- Play cu Torenter (pyrrent2http).

Daca mai ai ceva de adaugat, poti sa o faci.  Daca nu, poti inchide sesizarea.
Multumesc pentru  tot.
O seara placuta.

**Comment by xngsrs** [comment]
Nu mai am nimic de adaugat, daca ai rezolvat cu alte setari, e perfect.
