### ISSUE TITLE
MRSP si Trakt TV Shows

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#29]
Am mai gasit un bug. Il stiu de mai demult, dar atunci nu am mai folosit acesta optiune si acum vad ca tot nerezolvat este, asa ca am zis sa deschid un issue pe tema asta.
Este vorba despre ”Mark Watched Episodes” in Trakt. Momentan ma uit la Gotham. Sunt la sezonul 4.  Folosesc MRSP si torente. Iau de obicei un intreg sezon (freeleech) si ma uit la un episod (sa zicem s04.e01). Ei cand se termina si imi apare ”marcat ca vizionat in Trakt”, de fapt mi-a marcat ca vizionate toate sezoanele de Gotham(s01-s05), nu doar ep.1 din s04. Si apoi mi se sincronizeaza ca vizionate si in libraria din Kodi prin Exodus(eu pe el in folosesc pentru Sync) si nu mai stiu unde am ramas.
Un workaround e sa opresc din MRSP sync cu Trakt si sa o fac eu manual, dar e pacat daca tot este implementata aceasta facilitate, sa nu profitam de ea la maxim. 
La filme, merge ok. Doar la seriale e aceasta problema. Nu am testat cum se face Sync daca iau doar episoade individuale, caci dupa cum am zis, eu ma uit la cele care is freeleech si iau torente cu sezoane intregi. Sa fie oare asta problema si aici sa fie bugul?

Am deschis 4 issues azi cu bugurile care le-am gasit eu. Sper sa poti rezolva ceva, cand ai timp.
Multumesc! Si scuze daca ti-am dat batai de cap :)

**Comment by xngsrs** [comment]
De chestia asta cu serialele nu stiu ce sa zic, urmaresc si eu destule seriale si nu mi s-a intamplat niciodata ce zici tu. Nu am cum sa simulez la mine, pentru ca la mine functioneaza. Dupa ce se marcheaza episodul, imi apare in trakt numai ala ca vizionat. Nu mi s-a pus niciodata tot serialul ca fiind vizionat, in trakt.

**Comment by xngsrs** [comment]
Ok, mai incearca, apoi anunta-ma.

> Care sunt setarile corecte pentru Trakt? Eu am asa:

>    MRSP/Setari/Trakt - Marcare automata ca vizualizat in Trakt - ON
>    Arata episoade nelansate - OFF
>    MRSP/Setari/Misc - Monitorizare Trakt si din afara MRSP - ON.

In teorie orice setare ar trebui sa faca exact ce spune. "Arata episoade nelansate" este doar pentru sectiunea Trakt -> Calendar, unde vor aparea cu rosu, in partea de sus, episoadele nelansate si pe care le urmaresti. 

> Iar setarea urmatoare se refera doar la playerele din MRSP (elementum, torrenter) sau se refera si la Exodus, Numbers, ce le am in Kodi? E pusa pe ON.

>    MRSP/Setari/Misc - Adauga la Vazute - ON

De fapt este: MRSP/Setari/Misc - **Adauga la Vazute si ce vezi din afara MRSP** - ON, deci se refera la ce vezi din afara MRSP

**Comment by angelitto2005** [comment]
Am verificat ieri si azi pe win10 si pe OSMC. Pare sa marcheze ca vizionat doar episodul respectiv. Sper sa fi fost doar o eroare solitara ce s-a intamplat cu Gotham, Daca o sa mai fie probleme, o sa te anunt. Dar deocamdata e bine.
Dar, testand aceasta problema am dat de alta. La serialul MOM. Se pare ca sunt 2 seriale cu acelasi nume:
[Mom 2013](https://trakt.tv/shows/mom) care are 7 sezoane.
si 
[Mom 2015](https://trakt.tv/shows/mom-2015) care are doar un sezon.
Chestia  interesanta e ca il am bagat in Librarie pe cel din 2013 cu 7 sezoane, si  cand am facut teste, la s.01.e1-2, MRSP, mi le-a marchat ca vizionate la cel din 2015, care nu il am in librarie. Si am testat si la s.02 si s.04 iar aici nu le mai marcheaza ca vizionate deloc. Poate vede in Trakt ca cel din 2015 nu are decat s.01 si nu le mai marcheaza pe celelalte 6 sezoane de la cel din 2013. Cred ca poti testa si tu si poti replica problema.
Si tot legat de MOM, nu gasesc nici subtitrare la el pe Regie, Subs, sau Subtitrari-noi. Desi pe toate 3 siturile sunt toate sezoanele, se pare ca la search gaseste doar sez.5-6. Cred ca poti testa si asta. poate are legatura cu eroare din Trakt.
Am testat de curios si la un film, Carrie, care e si din 2013 si din 1976, dar aici l-a marcat corect pe cel din 2013. deci cred ca bug'ul e doar la TV Shows.
Aceste buguri, nu mi se par de importanta majora, dar am dat de ele si am zis sa ti le mentionez.

**Comment by xngsrs** [comment]
La treaba cu marcatul de episoade gresite chiar nu prea am ce sa fac. Marcarea ca vazute o fac eu prin extragerea informatiilor din numele fisierului, deoarece in informatiile disponibile pe site-uri nu sunt bagate id-ul imdb sau id-ul tvdb, pentru marcare exacta . La seriale, in numele fisierului nu este trecut si anul, doar numele, sezonul si episodul, ce iese din tipar nu va fi marcat, iar daca exista mai multe seriale cu acelasi nume, atunci apar neconcordante. 
La filme in schimb, in numele fisierului este trecut si numele filmului si anul, desi chiar si pe asta il mai gresesc ei cateodata, de aia va fi marcat cum trebuie, atata timp cat numele filmului este scris corect in numele fisierului.
Sistemul nu e nici pe departe perfect, dar atat cat este, functioneaza bine in mare parte.

La fel, faptul ca nu iti gaseste subtitrarea pentru anumite seriale sau filme, e din cauza numelui fisierului sau din cauza informatiilor filmului. Daca in numele fisierului apare de exemplu Mom.S03E03, atunci cautarea va returna rezultate, dar daca in numele fisierului avem doar Mom.S03 sau doar Mom.03 sau doar s03e03, nu iti va gasi subtitrarea corecta pentru episodul pe care il vizionezi si va trebui cautata manual, scriind in cautare manuala mom s03e03.
 Unele motoare de cautare de subtitrari pot cauta subtitrarea si in functie de numele complet al fisierului (cum ar fi opensubtitles, ca asa au facut site-ul si toata lumea uploadeaza fel si fel de subtitrari cu tot felul de nume) sau in functie de hash-ul fisierului (cum ar fi bsplayer), dar la noi nu exista niciun site care sa faca cautarea in asa fel, deci ne limitam la ce avem.

**Comment by angelitto2005** [comment]
Ok. Am inteles ideea. Daca nu se poate face nimic, asta e. Poate pe viitor 😄 Oricum acest bug nu ma deranjeaza asa tare. E prezent doar la Mom.
Poti inchide aceasta sesizare.

**Comment by xngsrs** [comment]
Ok, poate pe viitor, depinde de ce cunostinte acumulez.
