### ISSUE TITLE
MRSP

### ISSUE THREAD

**Issue by numelemeu** [xngsrs/myhobby#30]
Salut,
In primul rand multumesc pt.(movies ro site pack)acest addon, e al naibii de bun.
Acuma, o problema pe care o am este Filelist.Intru pe filelist, imi apar toate categoriile(filme, seriale, etc.)dar cand intru intr-o categorie, nu se populeaza, nu apare nimic si nu da nici o eroare.
Folosesc coreelec ultima versiune 9.2.2, pe un mecool m8s pro.
Seara buna!

**Comment by xngsrs** [comment]
Salut,
nu ma pot gandi decat ca ai bagat username sau parola gresita si a intrat domeniul in protectie pentru 1 ora. Verifica parola si utilizatorul, sa fie corecte, apoi reincearca peste o ora de la ultima incercare.

**Comment by angelitto2005** [comment]
Pot confirma ca la mine merge ok si pe windows si pe OSMC.
