### ISSUE TITLE
Rugaminte includere plugin

### ISSUE THREAD

**Issue by numelemeu** [xngsrs/myhobby#31]
Salut,

Crezi ca poti include si plugin-ul radiofly.ws  in romanianpack.
Pluginul vechi cel creat de jakeres nu mai gaseste link-urile cu filme, da urmatoarea eroare:

2020-05-02 19:52:53.711 T:4344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script 

returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\old-computer\AppData\Roaming\Kodi\addons

\plugin.video.radioflyws\default.py", line 382, in <module>
                                                SXVIDEO_FILM_PLAY(url)
                                              File "C:\Users\old-computer\AppData\Roaming\Kodi\addons

\plugin.video.radioflyws\default.py", line 108, in SXVIDEO_FILM_PLAY
                                                jsondata = json.loads(jsonlink)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", 

line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", 

line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--

Un sfat ceva?
P.S.: intradevar la filelist problema era de la parola introdus agresit.
Seara buna!

**Comment by shadowthu** [comment]
Vă rog frumos și eu, nu știu să deschid o temă nouă și scriu aici, apreciez de foarte mult timp repo ul sarsaila și va mulțumesc pentru tot ce faceți, dar de la 1 mai nu mai merge filelist în movies pack ro deoarece a schimbat site-ul pe filelist.io, știu că nu aveți timp dar vă mulțumesc pentru tot efort cu repo sarsaila, God Bless you

**Comment by xngsrs** [comment]
Salut,
@numelemeu Sunt deja 14 site-uri pentru filme online, nu vad motivul pentru care ar mai trebui unul in plus. Am mai avut cerinte pentru site-ul de care zici, dar mi s-a parut inutil. Din ce imi zici de addonul facut de jakeres, banuiesc ca nu mai functioneaza de ani de zile, nu de acum. O sa vad totusi, depinde in ce toane o sa fiu :)

@shadowthu Filelist merge fara probleme, chiar si de la 1 Mai, domeniul e schimbat in addon de ceva timp, nu stiu ce problema ai la conectare, dar nu e din cauza addonului.

**Comment by xngsrs** [comment]
@numelemeu M-am uitat pe site, nu o sa il fac, e facut prost, nu contine niciun fel de informatii ale filmelor, in afara de poza. Nu am cum sa il includ, nimeni nu va sti ce film e, ce nume are, din ce an e, daca nu se uita la poze. In plus de asta, unele filme sunt puse sub forma de arhiva. Nu stiu cine se uita pe site-ul ala, e o rusine de site.

**Comment by shadowthu** [comment]
Îmi pare rău site-ul mergea bine filmele erau și de 2k fără probleme, nu sunt un noob dar am instalat Kodi de 3 ori ieri și tot nu pornește filelist, îmi pare rău că am deranjat

Enviado desde Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by xngsrs** [comment]
@shadowthu Citeste te rog, cu atentie, cui ii raspund si ce :)
Filelist functioneaza fara probleme, asigura-te ca ai ultima versiune de MRSP:  1.0.80

**Comment by shadowthu** [comment]
Dar în repo sarsaila e addonu movies ro pack și toate torentele funcționează pe mrssplayer în afară de filelist, scuzați-mă că va deranjez și din moment ce merg toate rarbg, pirate Bay lime torent, kikass doar filelist nu face nimic când dau play,

Enviado desde Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by xngsrs** [comment]
@shadowthu Acum Movies Ro Sites Pack este la versiunea 1.0.81 .
Verifica sa ai versiunea asta instalata. 
Apoi verifica daca poti intra de pe pc, pe noul domeniu Filelist si daca ti-au blocat sau nu contul. 
Daca nu iti va merge in browser, nu o sa iti mearga nici in addon. 
Daca iti merge in browser si ai ultima versiune a addonului Movies Ro Sites Pack, trimite-mi [kodi.log](https://kodi.wiki/view/Log_file/Easy), dupa ce incerci sa intri pe filelist.

**Comment by eflorin** [comment]
Salut! iti semnalez exact aceasi problema pe care o are @shadowthu, nu merg filmele in filelist desi pana acum 5 zile era totul ok, adica pur si simplu nu porneste mrsplayerul cand sunt pe filelist. Am ultima versiune 1.0.81 de care spuneai mai sus. restul merg si kickass, 1337x etc ...mai putin filelist. Am incercat si cu torrenter si cu elementum. Apreciez eforturile tale, eu doar semnalez...

**Comment by shadowthu** [comment]
Îți mulțumesc mult pentru că îmi răspunzi la email am făcut ce mi-ai zis am instalat Kodi de 4 ori azi și nu am pus decât addonu din repo sarsaila movies pack ro 1.81 última updated si același lucru nu pornește playerul pe file, am întrat pe site e totul ok și apoi pe Kodi, toate torentele merg cu mrssplayer doar filelist nu face nimic nu pornește mrssplayer, scuza că îți tot răpesc din timp dar nu ajung la nimic logic și îmi vine să mă urc pe pereți, mulțumesc pentru răspunsul prompt și pentru timpul acordat dar tot nu merge filelist,

Enviado desde Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by angelitto2005** [comment]
LA mine merge fara probleme si pe OSMC si pe windows 10.
Dovada:
![screenshot000](https://user-images.githubusercontent.com/29383306/81226466-8df9ba80-8ff3-11ea-929c-3c255eece149.png)
![screenshot001](https://user-images.githubusercontent.com/29383306/81226474-9225d800-8ff3-11ea-90e9-3fa32a6a51fa.png)
![screenshot002](https://user-images.githubusercontent.com/29383306/81226479-93ef9b80-8ff3-11ea-956e-dce9cdfc252c.png)

**Comment by xngsrs** [comment]
@eflorin @shadowthu  Va inteleg, nu va merge. 
Problema este ca eu nu pot sa reproduc ce patiti voi.
 Mai mult decat atat, abia acum am inteles ca de fapt voua va arata continutul de pe filelist, dar nu va functioneaza download-ul. In mod normal, cand eu zic ca la mine merge, voi trebuie sa veniti cu alte informatii (cum ar fi kodi.log), ceva care ar putea sa ma faca pe mine sa inteleg sau sa reproduc problema.
Doar simplul fapt ca imi spuneti ca nu functioneaza, in timp ce mie imi functioneaza, nu ajuta cu nimic.
In fine, o sa merg pe ghicite si o sa fac o mica modificare, sper ca o sa functioneze. Daca nu, deschideti un issue nou, ca asta era pentru altceva decat probleme cu filelist. Si va astept cu fisier log.

**Comment by eflorin** [comment]
Multumesc! @xngsrs. Am descarcat "plugin.video.romanianpack-1.0.83" am actualizat, si merge perfect. Mult succes in tot ce faci!

**Comment by shadowthu** [comment]
Mulțumesc pentru tot ce faci mai ales pentru ca îți răpește din timpul tău, de aceea mă înclin cu respect și God Bless you and your family 👍totul funcționează la perfecțiune cu ultimul update 1.83, încă o dată mulțumesc și respect mă înclin, dacă toți ar fi ca tine lumea în care trăim ar fi un loc de neimaginat, salutări și multă sănătate

Enviado desde Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by xngsrs** [comment]
Ma bucur ca s-a rezolvat :)
