### ISSUE TITLE
[Idee] Addon(uri) de desene/anime

### ISSUE THREAD

**Issue by madnesofjuice** [xngsrs/myhobby#32]
Salut! M am gandit daca ai putea adauga vreun addon de desene / anime, dar sa nu fie ca si desene3d( deja e invechit). Uita te la kimdesene(nu sunt asa multe, dar sunt in claritate cat mai bune+o sa ma apuc sa postez mai multe) sau desene-super( aici sunt mai multe) sau chiar dozaanimata unde sunt destul de multe. Pentru anime ar fi anime-kage sau deseneanime. Am vazut ca pe netu. tv/hqq nu functioneaza sursele, daca te gandesti sa faci vreun plugin de desene as putea sa le urc si pe alte siteuri(mixdrop, jetload sau care mai merg)

**Comment by xngsrs** [comment]
Salut, 
nu prea am mai avut timp sa mentin asa multe addonuri si oricum multe au devenit inutile.
De ceva timp am mai inceput sa sterg din ele, cand imi aduc aminte, pentru ca nu isi mai au sensul. 
De creat addonuri separate, nici atat nu as avea timp. In cel mai bun caz as putea sa adaug in Movies Ro Sites Pack cate ceva. Munca de intretinere a catorva zeci de addonuri este prea mare pentru mine, de aia am preferat sa creez un addon care contine mai multe.
M-am uitat pe ce ai zis, kimdesene sau desene-super nu au sens, au numai o singura sursa pe netu, care asa cum ai mentionat si tu, nu merge. 
Deseneanime are protectie cloudflare pentru ddos, nu il voi adauga.
Dozaanimata si anime-kage par ok, o sa vad cand am timp si as putea sa le adaug in MRSP.

**Comment by madnesofjuice** [comment]
La acel ro sites pack ma refeream si eu, nu are rost sa faci alt plugind de la 0 cand poti adauga ina acela. Am zis ca daca vrei sa adaugi pot sa adaug si alta sursa care merge (videomega am vazut ca functioneaza), de asta te am intrebat daca ai timp sa adaugi in ro sites pack si astea.

**Comment by xngsrs** [comment]
Ok, cand voi avea timp e posibil sa le adaug. O sa las sesizarea deschisa pana le voi adauga, pentru ca nu cumva sa uit

**Comment by xngsrs** [comment]
Salut, am bagat de atunci un site de desene in MRSP, dozaanimata, nici pana acum nu are link-uri ok, deci nu o sa mai adaug altele.
