### ISSUE TITLE
Problema mixdrop

### ISSUE THREAD

**Issue by madnesofjuice** [xngsrs/myhobby#33]
Salut! Cand incerc sa deschid un link mixdrop nu ma lasa, imi da eroarea asta:
https://pastebin.com/wDKd0NhJ

Am incercat deja sa activez setarile astea si tot nu functioneaza: https://github.com/jdf76/plugin.video.youtube/issues/616

**Comment by buto01** [comment]
Hi, 
Mixdrop don't work now, I think  is down. Okstream, hqq.tv, dood. doesn't work properly, 
What can we do to have a good stream?
Thanks

**Comment by xngsrs** [comment]
Mixdrop functioneaza, acum. ResolveUrl este responsabil de streamurile gazduite.
