### ISSUE TITLE
Streamuri FS Online

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#34]
Salut,
Cred ca am o problema cu streamurile din MRSP in special cu cele din FS Online. Pe un Tv Box android, singurul stream care mergea era MixDrop. Acum da o eroare" Video not Found", HQQ.Tv, Ok stream si evoload nu au mers niciodata. Pe site lui FS Online, streamurile functioneaza, deci ma gandesc ca ar fi ceva de facut cu TV Box-ul, poate o setare, sau ceva ce lipseste. Ai putea sa ma ajuti?
Multumesc anticipat.

**Comment by xngsrs** [comment]
Mixdrop functioneaza, acum. UrlResolver este responsabil cu rularea streamurilor gazduite.

**Comment by MisuIancu** [comment]
Multumesc pentru informetie. Am remarcat ca UrlResolver nu reuseste sa faca updat la ultima versiune 5.1.3. S-ar putea ca ultima versiune de Kodi 18.7 sa fie de vina?
Mai am o intrebare unpic naiva, de ce celelalte streamuri, HHQ,OKstrea, nu functioneaza in Kodi ?
Multumesc mult.
