### ISSUE TITLE
FS Online 

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#35]
Salut,
Cred ca am o problema cu streamurile din MRSP in special cu cele din FS Online. Pe un Tv Box android, singurul stream care mergea era MixDrop. Acum da o eroare" Video not Found", HQQ.Tv, Ok stream si evoload nu au mers niciodata. Pe site lui FS Online, streamurile functioneaza, deci ma gandesc ca ar fi ceva de facut cu TV Box-ul, poate o setare, sau ceva ce lipseste. Ai putea sa ma ajuti?
Multumesc anticipat.

**Comment by xngsrs** [comment]
duplicate of #34
