### ISSUE TITLE
Streamuri care nu se deschid in MRSP

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#36]
Salutare,
Imi cer scuze pentru insistenta, dar am o mare nelamurire. Majoritatea streamurilor, in afara de MixDrop, nu se deschid in MRSP,pe un Android TV Box. Inteleg ca URLresolver sau ResolverURL sunt responsabile cu rularea streamurilor, dar care este solutia pentru vizionarea streamurilor cum ar fi Okstram,Hqq, dood.watch? Trebuie facuta vreo setare in addon, sau in setting resolvers?
Multumesc pentru ajutor.

**Comment by MisuIancu** [comment]
Cred ca am gasit singur raspunsul. In afara de Mixdrop, celelalte streamuri nu se afla pe listele de web host din resolver. Deci in afara de FS Online care are Mixdrop, celelalte site-uri de filme si seriale nu vor functiona. Exista vreo solutie?

**Comment by xngsrs** [comment]
Salut, sunt multe servere de streaming care functioneaza, din pacate nu sunt toate, pentru ca unele apar peste noapte, altele au recaptcha si nu se pot rezolva.
ResolveUrl este addonul care se ocupa cu decodarea lor. Inainte mai faceam si eu cate ceva in plus, dar am renuntat intre timp, pentru ca in general site-urile care au doar cate un link la un film nu merita osteneala. 
Solutii: - Iti faci un abonament platit la realdebrid sau alte servicii de genul, care preiau streamul de pe site-rile respective si ti-l livreaza tie fara probleme si folosesti alte addonuri, pentru ca in MRSP nu am implementat oricum chestiile astea, pentru ca nu detin vreun abonament la asa ceva. 
          - Folosesti partea de torrenti, cu elementum sau cu mrsp player, cum doresti.
