### ISSUE TITLE
Autosub

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#37]
Salut. Exista vreo sansa ca sa pui o excludere pentru addon'ul Youtube in Autosub? Intreb pentru ca de multe ori las youtube sa mearga si la cate un colaj mai mare si mi se opreste videoul si se deschide autosub. M-am gandit ca poate poti implementa o optiune de excludere sau ceva asemanator.
Un workaraound e sa setez sa se deschida autosub la peste 40 minute, caci marea majoritate a serialelor au peste 40min, dar sunt si care au mai putin si pe de alta parte sunt si destule colaje mari, asa ca tot nu am rezolvat nimic.

**Comment by xngsrs** [comment]
Salut, momentan poti băga in setari, pe langa celelalte doua cuvinte care deja exista, la sectiunea autosub -> "ingora cuvintele, separate cu virgula": _googlevideo.com_

**Comment by xngsrs** [comment]
Ok, am zis sa nu o las asa, am bagat o optiune in Setari -> Autosub, Exclude Addon, care trebuie activata, apoi introdus numele addonului la Nume Addon, de preferat sub forma in care vine, exemplu _plugin.video.youtube_. Poti adauga si numai cuvantul _youtube_, daca preferi.

**Comment by angelitto2005** [comment]
Multumesc frumos. Sanatate!

**Comment by angelitto2005** [comment]
Am testat ambele variante si se pare ca nu merge la colajele noi (nevizionate). Doar la cele vizonate. Daca dau pe un video nou, intotdeauna apare fereastra cu Autosub. Dau back si dispare. Apoi daca repornesc colajul respectiv, nu mai apare. Dar in momentul cand apare iar un video lung, Autosub e la datorie :)

**Comment by angelitto2005** [comment]
Acum vad ca merge. E ciudat totusi. Aseara am testat pe 2 dispozitive (Windows si OSMC). Pa amandoua aparea Autosub la colajele noi. Acum vad ca nu mai apare. Deci, totul e OK 👍

**Comment by angelitto2005** [comment]
Sal xngsrs. Cand ai timp, mai verifica o data te rog problema aceasta. Intotdeauna la primul play, la melodiile mai lungi (depinde cate minute am setat), apare autosub si cauta subtitrarea. Daca dau stop si play din nou, nu mai  apare. Deci doar prima data cand dau play apare si se opreste muzica. Sunt sigur ca si la tine se manifesta la fel. Poate mai poti imbunatati treaba asta. Daca nu poti, asta e. Mersi oricum.
