### ISSUE TITLE
MRSP torrent2http error

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#38]
Am o problema pe Tv Android Philips la MRSP si Torrenter. Nu vrea sa mearga nicicum cu torrent2http.
Nici daca in MRSP la ”Actiune la click” aleg ”Play cu MRSP (torrent2http)
si nici daca aleg ”browse” sau ”play cu torrenter” si in torrenter la setari aleg ”Torrent2http (libtorrent via http) .Mentionez ca am functionat si ca am facut si ultimul update si tot nu functioneaza?

![119487584_337453880839030_5793771633464015430_n](https://user-images.githubusercontent.com/71712221/93891409-0d163380-fcf4-11ea-9499-e1c0a22cd6c9.jpg)
![119476372_337453907505694_6784562367043178415_n](https://user-images.githubusercontent.com/71712221/93891419-0f788d80-fcf4-11ea-8b66-1643aec79cb9.jpg)
![119458450_337453827505702_7510262978505364755_n](https://user-images.githubusercontent.com/71712221/93891424-10a9ba80-fcf4-11ea-88b5-2be40cc285d4.jpg)
![119437039_337454030839015_3379212979328451951_n](https://user-images.githubusercontent.com/71712221/93891427-11dae780-fcf4-11ea-8549-9b9c17a88d31.jpg)

**Comment by xngsrs** [comment]
Salut, nu stiu ce problema ar putea fi, in ultimul timp am facut mai multe update-uri, inclusiv la clientul de torrenti. 
Chiar putin mai devreme am pus un update, asigura-te ca l-ai facut, apoi restarteaza aparatul si incearca iar.
Daca tot nu merge, te rog sa imi trimiti un fisier log, luat dupa ce ai activat din kodi -> settings -> system -> logging -> enable debug logging, si dupa ce iti da iar eroarea.

**Comment by DjS2020** [comment]
Mulțumesc imediat o sa fac update-ul și încerc. Revin cu un răspuns.

**Comment by DjS2020** [comment]
Tot asa da eroarea și după ultimul update.. da nu pot sa vad în Android tv ca să pot sa îți trimit log - ul..

**Comment by DjS2020** [comment]
![IMG_20200922_211545](https://user-images.githubusercontent.com/71712221/93921256-fdf5ac80-fd18-11ea-9250-6400fc6c8a55.jpg)
![IMG_20200922_211216](https://user-images.githubusercontent.com/71712221/93921283-04842400-fd19-11ea-9997-993e6a5c8f71.jpg)

**Comment by xngsrs** [comment]
Din pacate, fara un log, nu am cum sa imi dau seama ce se intampla. Din poze am observat ca eroarea este "failed download torrent2http". Am facut un update la torrent2http, la versiunea 0.4.1, care adauga un timp de asteptare intre doanload si dezarhivare, ma gandesc ca poate stocarea e mai lenta si nu are timp sa astepte downloadul. 
Vezi daca iti merge cu ultimul update 0.4.1, dar daca tot nu merge, asigura-te ca ai spatiu pe memoria pe care e instalat kodi.

**Comment by DjS2020** [comment]
Salut acuma ai reusit functioneaza perfect MRSP-ul .Multumesc mult de tot.

**Comment by xngsrs** [comment]
Ma bucur ca merge. Cu placere.

**Comment by DjS2020** [comment]
Te salut din nou. Iar a apărut eroarea aceasta. Și nu mai funcționează Mrsp.. Dacă poți rezolva ca ultima data ar fi perfect mulțumesc anticipat. Și scuze de deranj.
