### ISSUE TITLE
Subtitrare FS Online

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#39]
Salut,
Ma intrebam de ce subtitrarea in engleza existenta pe site, nu se transfera si in addonul MRSP in Kodi. Exista vreo setare care trebuie facuta? AutoSub este dezactivata si in addon si in Kodi.
Merci.

**Comment by xngsrs** [comment]
Salut,
subtitrarile existente in browser nu apar in addon pentru ca au nevoie de extragere speciala si nu m-am ocupat de asta in mod special.

**Comment by MisuIancu** [comment]
Inteleg. Mersi.
