### ISSUE TITLE
MRSP error again.

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#40]
Te salut din nou. Iar a apărut eroarea aceasta. Și nu mai funcționează Mrsp.. Dacă poți rezolva ca ultima data ar fi perfect mulțumesc anticipat. Și scuze de deranj.
![93921283-04842400-fd19-11ea-9997-993e6a5c8f71](https://user-images.githubusercontent.com/71712221/97575336-3dd54100-19f5-11eb-8e0b-a63448a70b84.jpg)

**Comment by xngsrs** [comment]
Salut, fara un log nu am cum sa te ajut, la mine functioneaza pe toate device-urile.
