### ISSUE TITLE
Adaugare site filme

### ISSUE THREAD

**Issue by scara78** [xngsrs/myhobby#41]
Buna,in primul rand multumesc pentru ce faceti, e un addon de nota 1000!
Va rog daca puteti sa includeti si https://filmele-online.com

Are foarte multe filme noi si subtitrate, plus ca in fiecare zi adauga filme bune.
Multumesc

**Comment by xngsrs** [comment]
Salut,
filmele-online.com nu va fi adaugat, deoarece nu are decat un server de play pentru majoritatea filmelor, server care nu este recunoscut de addonul ce se ocupa de extragerea linkurilor: resolveurl
