### ISSUE TITLE
SpeedApp error 

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#42]
Bună în primul rand vreau sa îți urez sărbători fericite și pline de liniște alături de cei dragi ție și un an cu cat mai multe reușite și realizări.
In al doilea.. În MRSP de ceva vreme nu mai arata torentele la SpeedApp era singurul care îl foloseam și funcționa fără buffer. Dacă poți rezolva cumva as fi recunoscător. Mulțumesc frumos.

**Comment by xngsrs** [comment]
Salut!
La mine functioneaza speedapp. Vezi daca ai ultima versiune la MRSP (movies ro sites pack), 1.1.21
Daca nu iti merge nici dupa update, pune aici un log sa vad daca iti apar ceva erori.

**Comment by DjS2020** [comment]
Din păcate nu pot pune log ca e tv android și nu îmi arată... 
![IMG_20201228_180332](https://user-images.githubusercontent.com/71712221/103227457-176d4c80-4937-11eb-9d21-d9aa45ee33ad.jpg)
![IMG_20201228_180345](https://user-images.githubusercontent.com/71712221/103227460-19371000-4937-11eb-9c8e-b94275db5e08.jpg)
![IMG_20201228_180350](https://user-images.githubusercontent.com/71712221/103227462-19371000-4937-11eb-879b-264af14891bc.jpg
)Am pus niște imagini, să fie de la tarkt menționez ca am Build Albina și activat tarkt ca în video de la Romy.. 🤷‍♂️

**Comment by xngsrs** [comment]
Verifica-ti contul pe pc, e posibil sa nu iti mai functioneze contul, sau
Baga parola si username-ul corect ( **mai nou la username pe speedapp ar trebui bagat e-mailul**).
Si o avertizare: ar trebui sa folosesti trackerele private numai cu optiunea de seed, daca nu vrei sa ai probleme cu ratia sau hit and run, altfel ar fi de preferat trackerele publice.
Nu stiu ce e build albina, traktul nu are nicio treaba.

**Comment by DjS2020** [comment]
Culmea e ca a funcționat pana acuma și acuma dintr-o data nu mai vrea.. Am pus și id și parolă și fac și seed nu e problema.. Problema e ca nu văd torrentele.. Oare să încerc să instalez din nou mrsp.?

**Comment by DjS2020** [comment]
Am reușit era de la parolă acuma le vad dar nu îmi pornesc nici cu mrsp player nici cu elentum.. Vreo sugestie.. Scuze de stess

**Comment by DjS2020** [comment]
Uitam sa precizez ca pe filelist pornește cu mrsp și elementum.. Și pe calculator pot downloada..

**Comment by xngsrs** [comment]
Ar trebui totusi sa fii atent la setari, la parola, username. Vezi unde ai setat calea pentru download, te uiti in log-uri sa vezi ce erori ai.

**Comment by DjS2020** [comment]
Din pacate nu pot vedea pe android tv log ca sa iti dau...am incercat am pus si kodi din nou si mrsp si am facut si alt cont speedapp si tot asa face ,vad torentele dar cand sa sa se deschida nu se intampla nimic nici cu mrsp player dar nici cu elementum nici macar sa descarc cu torrent asta pe tv android, in schimb pe calculator functioneaza totul perfect...si pe filelist si restul functioneza perfect..
