### ISSUE TITLE
MRSP

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#43]
Din pacate nu pot vedea pe android tv log ca sa iti dau...am incercat am pus si kodi din nou si mrsp si am facut si alt cont speedapp si tot asa face ,vad torentele dar cand sa sa se deschida nu se intampla nimic nici cu mrsp player dar nici cu elementum nici macar sa descarc cu torrent asta pe tv android, in schimb pe calculator functioneaza totul perfect...si pe filelist si restul functioneza perfect..
Chiar nu stiu ce sa ii mai fac, culmea e pana sa dea ei drumul la freelech pana pe 7 ianuarie a functionat sa fie ceva de la ei sau ar trebui un update..

**Comment by xngsrs** [comment]
Da, a fost vina mea, ca nu am testat pana la capat.
Scuze ca a durat atat, am rezolvat in versiunea 1.1.24.
