### ISSUE TITLE
MRSP

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#44]
Salut ma scuzi ca te deranjez din nou am o mica problema cu Mrsp in kodi, de fiecare data cand vizionez un serial cand sa vad pe urmatorul mi se tot inchide kodi , daca vad de pe alte surse nu din mrsp functioneza stii cumca care ar putea fi problema ?? Nu pot lasa log ca ma uit pe android tv sa fie cumva ca am memorie librea de ram de 400 mb din 2 gb?? pt stocare am un hdd extern..?? Intreb ca nu facea inainte problemele acestea dupa cateva update-uri la mrsp a inceput sa le faca??

**Comment by xngsrs** [comment]
Salut, cand vrei sa vezi urmatorul episod se inchide? 
Ai activat descarcare automata urmatorul episod?
Ai activat sa inceapa automat?
Se inchide kodi cu totul?
Eu fac testele in general pentru modurile in care il folosesc eu. Am activat sa descarce urmatorul episod in timp ce ma uit la alt episod. Am activat sa ma intrebe daca porneste urmatorul episod. In alte conditii nu am mai testat.
Nu ar trebui sa aiba legatura cu cantitatea de ram ramasa, pentru ca un episod tot vezi.

**Comment by DjS2020** [comment]
Deci nu e vorba ca vad un sezon intreg nici asa nu apuc ca iese de tot din kodi si trebuie sa intru din nou deci nu stiu dc ca inainte a mers fara probleme, doa in MRSP face asa cand vreau sa ad de la filelist sau speedapp. valabil si la filme nici nu apuc sa vad inceputul ca se inchid kodi da crash...atat pe celelate merge bine mai iese si acolo cateodata da f rar..nu imi pot explica

**Comment by DjS2020** [comment]
Spre exemplu acuma am dat drumul la un ep de pe Speedapp a mers 2 min și s-a închis kodi..

**Comment by xngsrs** [comment]
Intra la setari mrsp si micsoreaza numarul de conexiuni la 35. Apoi limiteaza viteza de download la maxim 10MB, bagi 10000 in setari.

**Comment by DjS2020** [comment]
Hai ca încerc acuma și revin. Îți mulțumesc.

**Comment by DjS2020** [comment]
![IMG_20210120_215459](https://user-images.githubusercontent.com/71712221/105227768-5f644580-5b6a-11eb-8cbc-1dce5e556c14.jpg)
![IMG_20210120_215620](https://user-images.githubusercontent.com/71712221/105227782-625f3600-5b6a-11eb-9386-8b339c209a66.jpg)
Acuma nu mai pornește deloc..

**Comment by DjS2020** [comment]
Salut am revenit cu setările respective după un restart la kodi merge perfect am văzut chiar 2 ep unul după altul fără sa se mai inchida kodi. Îți mulțumesc mult de tot pentru răbdare și ajutor. Toate cele bune.

**Comment by DjS2020** [comment]
Am dat inapoi la setarile initiale si nu da numai erroare..acuma ma uit cu elementum.

**Comment by xngsrs** [comment]
Sa inteleg ca ai rezolvat. Folosesti elementum. E perfect, atunci. Inchide sesizarea daca nu mai e nevoie de ea.

**Comment by DjS2020** [comment]
Salut. am observat ca tot mai iese . In fine..Ce am observat e ca e mult mai stabil kodi 19 matrix dar din pacate nu merge mrsp-ul pe el,  il instaleaza dar nu poti viziona..pacat!

**Comment by xngsrs** [comment]
Si din nou incepem, acum cu kodi Matrix. 
Daca nu stiu ce erori ai, cum as putea sa le rezolv?
Tu ce ai face in locul meu? Cum ai putea rezolva problemele daca nu stii care sunt? 
Pe telefonul meu cu android si kodi 19 beta 2 a mers perfect. A mers, pentru ca azi am pus un update si nu mai merge. 
Cand o sa iasa kodi 19 stabil o sa vedem. 
Pana atunci, cand mai ai vreo problema, ataseaza-mi un log. Logurile se gasesc si pe android, ca si pe linux sau windows

**Comment by xngsrs** [comment]
P.S. Imediat scot versiune pentru kodi 19, in maxim 1 ora

**Comment by xngsrs** [comment]
E gata si versiunea pentru kodi, actualizata. Am testat pe kodi 19 beta2 android, curat. Doar ca dupa ce incerci sa pornesti un torrent, trebuie oprit kodi si pornit iar, din mendiul lui de power, pentru ca nu incepe descarcarea torrentilor

**Comment by DjS2020** [comment]
Multumesc si scuze de bataile de cap care ti le dau..sa inteleg ca trebuie facut asa la fiecare torrent sau doar la inceput?

**Comment by xngsrs** [comment]
Doar prima data dupa instalare si doar daca nu se conecteaza la peers.

**Comment by xngsrs** [comment]
Banuiesc ca se poate inchide aici, probabil ca ai rezolvat.

**Comment by Test9077** [comment]
Salut as vrea daca ma Poti ajuta cu o setare in MRSP
Folosesc Albina wizard iar posturile tv se opresc dupa 2-3minute, merg cu elementum in play nu am destula memorie in tv
O Alta problems daca instalez pe curat MRSP in kodi si deschid clicksud filme nu gaseste linku sa accesez nu stiu ce sa mai instalez
