### ISSUE TITLE
MRSP player nu porneste

### ISSUE THREAD

**Issue by eulaur69** [xngsrs/myhobby#45]
Salutare.
Am instalat MRSP pe windows si am o problema : cand incerc sa deschid un torrent imi da o eroare, si ma indruma sa ma uit peste log-uri.
Mentionez ca aceeasi problema o am si cand dau play cu torrenter.
Cand dau play cu elementum merge, dar nu gaseste subtitrarea automat, si cine o sa foloseasca plugin-ul nu stie sa caute subtitrarea manual.
O sa postez si log-urile. Am incercat sa deschid torrente de pe Yify si YourBittorrent.
https://pastebin.com/EWC6MQQT

**Comment by xngsrs** [comment]
Salut.
O sa investighez. Posibil sa fie niste erori pentru ca nu am mai facut test pe windows dupa ultimele update-uri.

**Comment by xngsrs** [comment]
Fa update la suplimentele kodi, ar trebui sa se actualizeze si mrsp si torrent2http. Sa ma anunti daca functioneaza.

**Comment by eulaur69** [comment]
Merge acum. Multumesc!

**Comment by xngsrs** [comment]
Perfect.
