### ISSUE TITLE
Compatibilitate Kodi Matrix pentru suplimentele de subtitrari

### ISSUE THREAD

**Issue by Xander-ro** [xngsrs/myhobby#46]
Salut, am instalat Kodi Matrix RC pe un CGTV. Vroiam sa știu dacă o sa faci curând modificările necesare pentru compatibilitate sau ma întorc la Leia? Multumesc

**Comment by xngsrs** [comment]
Salut. Cu matrix beta 2 in android e compatibil.
Pana cand nu intra matrix rc pe androidul meu, nu am cum sa testez mai departe.

**Comment by Xander-ro** [comment]
Am făcut actualizările, tot nu merge. Niciun supliment pentru subtitluri nu merge. Toate dau eroare cum deschid fereastra pentru descărcare subtitrări.

**Comment by xngsrs** [comment]
Nu mi-ai spus despre care addonuri este vorba, de la inceput. Am presupus ca e vorba de MRSP. 
Nu stiu, ramane sa le fac pe cele de subtitrari in curand.

**Comment by Xander-ro** [comment]
Scuze, nu mi-am dat seama. Am crezut ca un repo se actualizează, nu fiecare supliment în parte. Oricum, primește aprecierea și mulțumirile mele pentru tot ceea ce faci!

**Comment by xngsrs** [comment]
Repo este depozit. Depozitul nu se actualizeaza decat foarte rar, cand se schimba niste adrese. 
Depozitul nu se actualizeaza, marfa din el se actualizeaza.
Suplimentele din el sunt "marfa". Marfa se actualizeaza mai mereu, cand este nevoie.

**Comment by DjS2020** [comment]
Kodi matrix RC 1 am și eu și nu funcționează mrsp..asteit poate o sa rezolvi tu CV... P. S. Este la ei pe site kodi matrix RC pt android..

**Comment by xngsrs** [comment]
@Xander-ro subsro, regielive si subtitrarinoi sunt gata pentru kodi 19. Poti sa le actualizezi si vezi daca functioneaza.

@DjS2020 ca de obicei, nu spui ce nu iti functioneaza. Daca iti functioneaza prost, reseteaza box-ul si instaleaza pe curat, tot.
