### ISSUE TITLE
Compatibilitate MRSP cu Kodi 19

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#47]
Acuma am încercat sa îți scriu dar am văzut ca ai închis topicul.. Deci nu funcționează mrsp în kodi 19 nu se conectează mrsp scrie verific dacă exista în serversi iese.chisr și după restart kodi

**Comment by xngsrs** [comment]
Dezactiveaza MRSP server si reporneste aparatul pe care e instalat. In rest, mai incearca si alti torrenti, nu te bloca intr-unul singur. Sunt mai multi provideri in MRSP.

**Comment by DjS2020** [comment]
Am observat ca ai făcut un update și acuma funcționează sub.. Dar eu zic ca în MRSP scrie asa:Verifica și după ce verifica în loc sa pornească da eroare asta pe toate filelist Speedapp.. Se închide, am instalat și elementum și nu pornește.. Deci eu vroiam mrsp seed.. De uitat ma uit pe The oath.. Și seren care sunt singurele care îmi funcționează pe kodi 19 matrix RC. Menținez ca am șters și instalat toate  pe curat și la fel. Nu cred ca e de la mine.Imi cer scuze ca nu îți pot arata log dar nu le vad pe tv android.

**Comment by xngsrs** [comment]
Ok, o rezolv eu pana la urma.

**Comment by xngsrs** [comment]
Pana la urma, am zis sa incerc si matrix rc1. Din pacate mie mi-a mers si speed si filelist. Oricum ar fi, am mai gasit cateva chestii de reparat pentru kodi19 si am pus update-ul. 
Daca nu iti merge nici acum, inseamna ca ai alte probleme si nu ma privesc pe mine.
Eventual mai astepti putin pentru ca fac un update la torrent2http, desi nu cred ca ala e problema ta.

**Comment by DjS2020** [comment]
Întru imediat sa văd și o sa astept și update-ul la torrent. Eu îți mulțumesc mult de tot pentru răbdare. Oricum apreciez și revin după ce fac uptate ul.

**Comment by DjS2020** [comment]
Din pacate la fel asteapta sa verifice si se inchide..am si instalat din nou kodi si tot asa...e ceva cu kodi 19 matrix rc ..asta mai astept poate o sa reusesti tu sa ii dai de cap intr-o zi!

**Comment by xngsrs** [comment]
Nu am cum "sa ii dau de cap" daca eu nu pot reproduce problema ta. Am kodi 19 matrix rc1 pe android 9, merge foarte bine.
Pana nu imi dai un log cu eroarea, nu am cum sa te ajut...si nici atunci nu e sigur, dar macar as stii unde sa ma uit.
De atata timp ai fi putu sa te uiti si tu pe net sa vezi cum sa imi dai un log. Ai addonuri oficiale in kodi repo care iti arata log-ul si care chiar il si urca undeva si iti returneaza link-ul.

**Comment by DjS2020** [comment]
Am înțeles.. Când poți poate îmi lași în video unde sau cum pot vedea sa îți trimit log ul.. Sau cum sa fac în kodi setare sau de adon sa folosesc pt kodi 19 sa pot vedea.. Mulțumesc.

**Comment by DjS2020** [comment]
[kodi.log](https://github.com/xngsrs/myhobby/files/5898200/kodi.log)
E ok ce ți am trimis.. Poți vedea log ul.

**Comment by DjS2020** [comment]
[kodi.old.log](https://github.com/xngsrs/myhobby/files/5898215/kodi.old.log)
Acestea 2 le am găsit în temp.. Kodi. Sper sa te ajute cu ceva..

**Comment by xngsrs** [comment]
In sfarsit :)
Da, in kodi.log vad eroarea. O sa incerc sa o reproduc, dar se poate rezolva destul de usor.

**Comment by DjS2020** [comment]
Chiar  în sfârșit.. 😁 Atunci aștept și sa îmi spui dacă era de la mine sau de la mrsp.

**Comment by xngsrs** [comment]
Vezi acum, ca am pus un update, v.1.1.35
Nu am putut sa reproduc eroarea, dar am ocolit-o. Daca mai apare, imi pui iar un log, cu noua eroare.

**Comment by DjS2020** [comment]
În sfârșit ai reușit sper sa tina de acuma. Mulțumirii un weekend plăcut. Seara frumoasa.

**Comment by xngsrs** [comment]
De aia e bun un log :)
