### ISSUE TITLE
MRSP player porneste greu

### ISSUE THREAD

**Issue by angelitto2005** [xngsrs/myhobby#48]
Salut. De vreo doua zile, playerul porneste greu de tot.  Am testat si pe  OSMC si pe Windows. Pe amandoua am Kodi 18.9. Inainte dura maxim 15 secunde si pornea filmul. Acum dureaza mult mai mult. Pe PC, desi descarc si cu 20-30 mb/s, porneste dupa cateva minute (vezi video), insa pe OSMC e nasoala treaba. Descarca cu maxim 10 mb/s si dureaza si cate 15 minute pana porneste. Si daca setez prebuferul la 50mb, stau cred ca juma de ora 😄 Inclin sa cred ca e de vina torrent2http. Am observat problemele astea de cand am facut update la 1.1.33
Cu 1.1.31 si versiuni mai vechi mergea super bine.
Am mai observat o chestie. Descarca intotdeauna si ep.1 din sezon, chiar daca eu dau sa descarce ep.6. Poate e o eroare si aici. Inainte aveam activata si optiunea sa descarce si episodul urmator in timp ce-l vizionam pe cel actual, dar parca dureaza si mai  mult pana porneste filmul cu acea optiune activata, asa ca am dezactivat-o dar tot nu e mare diferenta.
 Sper sa-i dai de cap caci e un addon foarte bun si foarte folositor.
Keep the good work! 👍 
Thanks!

https://user-images.githubusercontent.com/29383306/106139323-f4240000-6175-11eb-975c-e343d5d958eb.mp4

**Comment by xngsrs** [comment]
Salut.
Din pacate stiu, asta se intampla la seriale, cand sunt mai multe fisiere intr-un torrent. Din pacate nu pot sa ma mai intorc inapoi la vechea versiune.
Imi storcesc creierii, imi scapa ceva si nu stiu ce.
Sper sa reusesc sa fac ceva.

**Comment by angelitto2005** [comment]
Sa inteleg ca ai trecut la Matrix si nu te mai intorci la 18.9? Daca la asta te referi si daca la Matrix nu sunt aceste probleme, voi trece si eu pe PC la el, nu e problema.
Problema e la Vero 4k (OSMC) unde inca nu au bagat update-ul de Matrix. Si il am conectat la TV. Eu acolo ma uit seara.
Un workaround (sa zic asa) ar fi sa-mi trimiti buildul de 1.1.31 pentru OSMC? In felul acesta o sa-l setez (mrsp) sa nu se mai actualizeze automat si voi ramane asa o vreme, pana cand va aparea Matrix stabil si il vor actualiza si cei de la OSMC. 
Ma gandesc ca poate mai ai prin PC versiuni mai vechi de MRSP: 1.1.31 sau 1.1.30, sau chiar 1.1.2929. Oricare din ele ar fi super. Impreuna si cu versiunea mai veche de torrent2http.
Daca nu le mai ai, atunci raman asa ca nu am ce face.

**Comment by xngsrs** [comment]
Nu, nu asta am vrut sa zic. E vorba de binarul torrent2http, care este scris in golang. La cum stiu eu golang (aproape deloc), m-am incurcat putin in cod. **O sa ii dau de cap, pana la urma.**
Versiunile vechi de torrent2http erau prea vechi si a trebuit sa continui cu ceva mai nou.

**Comment by angelitto2005** [comment]
Ok, am inteles. Totusi daca nu reusesti, sau daca dureaza, zile sau chiar saptamani, trimite-mi te rog un ”torrent2http” si un mrsp mai vechi, provizoriu, pana reusesti sa-i dai de cap.

**Comment by xngsrs** [comment]
Am rezolvat, maine il pun online, acum e prea tarziu, ma bag la film :)

**Comment by angelitto2005** [comment]
Ooo, super. Sincer nu credeam sa rezolvi asa rapid, mai ales ca ai zis de problemele ce le-ai intampinat cu ”Golangul” :)
Atunci astept maine update-ul sa pot testa. Update-urile sunt intotdeauna binevenite, atat timp cat imbunatatesc si nu strica ce e bun si merge :) 
O seara faina!

**Comment by xngsrs** [comment]
Rezolvat in https://github.com/xngsrs/myhobby/commit/7ed30a23709422cdbf8b81a3e657cf8d902b0931

**Comment by angelitto2005** [comment]
Am testat si acum vad ca merge brici. Multumesc inca o data! 👍
