### ISSUE TITLE
MRSP Torrent

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#49]
Buna ma scuzi ca te deranjez din nou stii cumva cum pot sa vad torrentele de pe mrsp ma refer la web o adresa?? Ca in transmission nu merge sa le las la seed. Da eroare.Multumesc.

**Comment by xngsrs** [comment]
Pentru torrentii pe care ii ai la seed in mrsp, care nu ar trebui sa fie mai mult de 2-3 torrenti, decat daca ai memorie ram destula: http://ip-aparat:2829/stat  (inlocuiesti ip-aparat cu ip-ul aparatului pe care ruleaza torrent2http).
Sau poti sa ii vezi in sectiunea Intern Torrent.
Seed cu transmission nu merge decat daca ai transmission instalat undeva, cu transmission web activat, iar setarile de conectare le vei face din setari MRSP -> Torrent Client. Teoretic ar mai functiona seed-ul transmission si cu utorrent sau qbittorrent sau deluge, dar nu am mai testat functionalitatea lor, cel putin cu toate schimbarile aduse cu kodi 19.

**Comment by DjS2020** [comment]
Am incercat dar nu se pot descarca nici cu mrsp si nici nu transmission mentionez ca am instalat si pe tv transsmisiion si in kodi. si curios este ca nu pot sa vad nici torentele in adresa respectiva desi am activat optiunea MRSP server.O sa iti las un log
[kodi.log](https://github.com/xngsrs/myhobby/files/5903779/kodi.log)

**Comment by DjS2020** [comment]
App iar nu mai funcționează mrsp e aceeași eroare cu verificare și da eroare..

**Comment by DjS2020** [comment]
Salut am observat ca ai făcut update la torrent 2..dar tot nu pornesc torrentele pe Speedapp.. Cele de pe celelalte torrente pornesc perfect cu mrsp.. Curios..

**Comment by DjS2020** [comment]
Salut am observat ca ai lasat postul deschis si ai facut si un update nou la kodi matrix  19..dar tot nu functioneaza speedapp o sa iti las si un log mai tarziu poate o sa rezolvi tu cand ai timp acuma ca e oficial kodi 19.

**Comment by DjS2020** [comment]
[
[kodi.log](https://github.com/xngsrs/myhobby/files/6054419/kodi.log)
](url)

**Comment by xngsrs** [comment]
Salut, nu reușesc deloc sa reproduc problema din log. Acolo pare ca nu ai drepturi de scriere pe suportul pe care vrei sa salvezi. 
In afara de faptul ca ai mai multe erori de la mai multe addonuri.
Resetează setările kodi și baga doar folderul de download in setările mrsp. Folderul de download trebuie să aibă spatiu destul pentru ce descarci tu și trebuie să aibă drepturi de scriere.
O să las asta deschis, deși chiar nu am cum sa reproduc eroarea.

**Comment by xngsrs** [comment]
@DjS2020 Am facut un update acum, am reusit sa reproduc problema. Te rog sa actualizezi mrsp si torrent2http la 1.1.43 respectiv 0.5.10 si sa imi spui daca e totul in ordine. Asta daca mai folosesti cumva mrsp cu torrent2http.

**Comment by DjS2020** [comment]
Salutare am facut update functioneaza perfect acuma.Iti multumesc frumos!  zi frumoasa.Desgur ca folosesc! :D

**Comment by DjS2020** [comment]
Am observat ca ai făcut iar update de la 43 la 44 ai iar nu funcționează 🤦‍♂️

⁣Obțineți BlueMail pentru Android ​

Pe 4 mar. 2021, 20:07, la 20:07, Sarsa <notifications@github.com> a scris:

**Comment by xngsrs** [comment]
@DjS2020 , este imposibil sa nu iti mearga din cauza update-ului dintre 43 si 44, pentru ca la 44 doar am reparat o problema cu marcarea ca vizionat in trakt.
Daca nu iti merge iar ceva, e posibil sa fi nimerit tu o situatie speciala, iar. Trebuie sa imi dai un log.

**Comment by DjS2020** [comment]
Numai eu is cu stituatiile speciale ca doar nu fac nimica :))) doar ce a facut update si nu a mai functionat.. uite iti las si log-ul
[kodi-2.log](https://github.com/xngsrs/myhobby/files/6095316/kodi-2.log)

**Comment by xngsrs** [comment]
@DjS2020 Nu am vazut nicio eroare in kodi-2.log, la mrsp, cu exceptia uneia inofensiva atunci cand ai oprit kodi.

**Comment by DjS2020** [comment]
Da asa este am deschis acuma și observ ca funcționează. Mulțumesc și un week-end liniștit. 

⁣Obțineți BlueMail pentru Android ​

Pe 6 mar. 2021, 17:28, la 17:28, Sarsa <notifications@github.com> a scris:
