### ISSUE TITLE
Movies ro site pack

### ISSUE THREAD

**Issue by visinel** [xngsrs/myhobby#5]
Filmeonline2013.biz nu functioneaza,nu arata filmele uracate pe site ,multumesc

**Comment by visinel** [comment]
Filmeonline2013.biz nu functioneaza,nu arata filmele uracate pe site ,multumesc

**Comment by xngsrs** [comment]
Rezolvat in https://github.com/xngsrs/myhobby/commit/c39eafc804051dab4a15f8275f1c40d72b43be3c
