### ISSUE TITLE
MRSP no seed

### ISSUE THREAD

**Issue by DjS2020** [xngsrs/myhobby#50]
Te salut am observat ca nu mai stau torentele la seed in MRSP e ceva de la tine sau...dupa vizionare spune ca s-a adaugat la seed dar nu stau. nici nu le vad in web??

**Comment by DjS2020** [comment]
![ops1](https://user-images.githubusercontent.com/71712221/111807351-87a6c100-88db-11eb-8b97-72dc8afb6c52.jpg)

**Comment by xngsrs** [comment]
Vezi ca am facut acum un update la mrsp si torrenter. Banuiesc ca nu iti porneau torrentii de la seed dupa ce opreai kodi. Ca alta problema nu am vazut.

**Comment by DjS2020** [comment]
Salut acuma functioneaza foarte bine.Dar am o problema de fiecare data cand deschid mrsp ul imi descarca in fundal si alte torente mai vechi am dat si kill si a doua zi mi-o ia ia iara de la capat cum pot sa fac sa nu le mai descarce..am instalat si kodi din nou si tot asa..?

**Comment by xngsrs** [comment]
Deoarece kill nu este delete. e doar kill. 
Stop si sters fisierele e bagat doar in "Intern Torrent" din MRSP. In interfata web nu am bagat niciun buton de stergere.
Daca dai doar kill, fisierul de resume_data ramane in folderul .resume in locatia unde e descarcat torrentul. Cand porneste MRSP, ia toate fisierele de resume ramase acolo. Se pot sterge manual sau din meniul de care ti-am zis mai sus: "Intern Torrent".

**Comment by DjS2020** [comment]
M-am uitat în MRSP dar nu știu unde e intern torrent.. Când poți și ai timp poate îmi lași un print ceva mulțumesc frumos.. Din cauza ca îmi descărca torrente vechi șterse din HDD mi se tot închide kodi.. 

⁣Obțineți BlueMail pentru Android ​

Pe 25 mar. 2021, 16:01, la 16:01, Sarsa ***@***.***> a scris:

**Comment by xngsrs** [comment]
![Screenshot_20210325_173603](https://user-images.githubusercontent.com/29460977/112500320-30439d80-8d80-11eb-84e4-cb1ee5a4699e.jpg)
![Screenshot_20210325_173536](https://user-images.githubusercontent.com/29460977/112500371-39346f00-8d80-11eb-8c86-6378360f8a8c.jpg)
![Screenshot_20210325_173512](https://user-images.githubusercontent.com/29460977/112500379-3afe3280-8d80-11eb-882f-792a40d11d24.jpg)

**Comment by DjS2020** [comment]
Am priceput acuma. Mulțumesc mult de tot. 🙏

⁣Obțineți BlueMail pentru Android ​

Pe 25 mar. 2021, 17:39, la 17:39, Sarsa ***@***.***> a scris:

**Comment by DjS2020** [comment]
Am încercat dar degeaba îmi iese prea repede din kodi și nu apuc sa le șterg.. 😐 Dacă închid opțiunea de la mrsp server merge fără probleme cum o deschid se deschide și după ceva timp mi se închide kodi de o e de la seeduri numai nu reușesc sa le șterg.. Dacă o sa poți adaugă un buton sa le poți pune pauză cumva la toate.. 

⁣Obțineți BlueMail pentru Android ​

Pe 25 mar. 2021, 17:39, la 17:39, Sarsa ***@***.***> a scris:

**Comment by xngsrs** [comment]
Am facut iar un update la torrent2http si MRSP. 
Am bagat o optiune activata implicit pentru a porni serverul cu torrentii in pauza (in setari -> "MRSP Torrent Player"). Pentru a-i porni, am bagat optiune la clic dreapta in "Intern Torrent" cu Start Torrent. 
Vezi cum e. Daca tot ti se inchide kodi, inseamna ca trebuie sa stergi manual folderul ".resume" din locatia de download stabilita in  setari-> "Torrent Download Folder". 
Atentie, folderul ".resume" este ascuns, deci sa iti setezi afisarea de foldere ascunse la file manager, daca vrei sa il stergi manual.

**Comment by DjS2020** [comment]
Daaaa ai facut o treaba foarte buna .acuma nu mai iese si e mult mai ok iti multumesc frumos!     On Sunday, March 28, 2021, 04:08:10 PM GMT+3, Sarsa ***@***.***> wrote:  
 
 


Am facut iar un update la torrent2http si MRSP.
Am bagat o optiune activata implicit pentru a porni serverul cu torrentii in pauza (in setari -> "MRSP Torrent Player"). Pentru a-i porni, am bagat optiune la clic dreapta in "Intern Torrent" cu Start Torrent.
Vezi cum e. Daca tot ti se inchide kodi, inseamna ca trebuie sa stergi manual folderul ".resume" din locatia de download stabilita in setari-> "Torrent Download Folder".
Atentie, folderul ".resume" este ascuns, deci sa iti setezi afisarea de foldere ascunse la file manager, daca vrei sa il stergi manual.
