### ISSUE TITLE
 mrsp 1.1.49 

### ISSUE THREAD

**Issue by softusgsm** [xngsrs/myhobby#52]
Pe ultimul update de la mrsp 1.1.49 nu mai exista streamuri la filmeonline 2016

**Comment by xngsrs** [comment]
Salut, au schimbat ei ceva, s-a rezovat in 9d5bad2

**Comment by softusgsm** [comment]
Salut. Tot nu merge. Apar streamurile dar da eroare ca nu poate importa jsunhunt.

**Comment by softusgsm** [comment]
Cu versiunea 1.1.48 doar youtube apare la stream
