### ISSUE TITLE
Trakt si TMDB

### ISSUE THREAD

**Issue by audiosistem** [xngsrs/myhobby#54]
Salut,scuze deranjul,ar tine de setarile proprii,ca ceea ce vizionez in MRSP,sa fie contorizat in trakt tv si sa-mi apara(bifa vazut)si-n TMDB helper?Cu stima si multumiri!

**Comment by xngsrs** [comment]
Salut!
Offtopic: Credeam ca sunt singurul care mai foloseste Kodi :))
Ontopic: In setarile MRSP ai rubrica pentru **trakt**, unde ai **Autorizare** ( care iti va permite sa conectezi contul trakt cu MRSP) si ai si **Marcare automata ca vizualizat in Trakt** ( care va trimite catre trakt semnalul ca ai vizionat un episod dintr-un serial sau un film, dar nu si daca l-ai vizionat partial, adica mai putin de 90%)
Daca ai acelasi cont de trakt conectat si la TMDb Helper, toata treaba ar trebui sa functioneze cum trebuie.

**Comment by audiosistem** [comment]
Salut,
onn:Functioneaza perfect,ce spui si setarile-s facute asa,ce vad prin intermediul TMDB helper(varii addon video),se contorizeaza-n Trakt si-n MRSP...e problema e viceversa.
off:Ce-l mai roade lumea(lumea noastra mica,RO).:))

**Comment by xngsrs** [comment]
Nu are nicio treaba addonul lui jurialmunkey, nu cu asta. Mie imi apar filmele si serialele vazute, la el in cont. 
Probabil ca problema consta in altceva, inca nu am verificat:
 Eu m-am concentrat pe marcarea filmelor in functie de numele fisierului, pentru ca folosesc 99,9% MRSP torrent. Atunci cand rulezi un film online, numele fisierului este irelevant si de aici buba. Inca o data, nu sunt convins, dar e posibil asa sa fie.
Treaba e ca daca nu iti apare mesaj de la MRSP, dupa ce inchizi filmul, ca a fost marcat ca vizionat, atunci cu siguranta nu a fost marcat ca vizionat si nu va fi nici in trakt. 
Metoda mea de extragere a numelui filmului este ...failibila :) dar am ajuns la solutia asta pentru ca nu am cum sa fac rost de id-ul exact al filmului de pe site-urile pe care le scanez.
Daca tot codul ala pus ca sa gaseasca filmul sau serialul si episodul, da gres, in sensul in care trakt nu il recunoaste dupa toate datele pe care le bag, atunci ele nu vor fi marcate. 
In 99% din cazuri, totusi, la mine le recunoaste si e ok, am totul marcat in trakt.

O sa verific sa vad ce gresesc eu, dar asigura-te ca iti apare notificare la oprirea filmului, ca a fost marcat ca vizionat in trakt.

P.S. Marcarea ca vazut se face dupa ce filmul oprit a trecut de 80% din timpul de vizionare (ca sa rectific ce am zis mai sus: ca s-ar face dupa 90%)

**Comment by audiosistem** [comment]
Tot ce spui este perfect corect si asa se si intampla.Problema efectiva este doar marcarea vazut,in TMDB,dupa ce am vizionat in MRSP.Daca intru in MRSP,arata marcat vazut,dar in TMDB nu mai apare bifa.La celelalte(ex.Crew,Oath,Alvin...)se bifeaza si in addon si in TMDB.

**Comment by xngsrs** [comment]
Aha, gata, am priceput acum.
Filmele sunt marcate si acolo si acolo, pentru ca folosesc tmdb id sau imdb id, numele si anul standard, pentru ca sunt toate luate din liste de pe tmdb. Asa este logic au acelasi id, intra in baza de date a kodi unde vor fi recunoscute ca atare. 
La mine, pe de alta parte, nu se face nimic dupa tmdb, listele cu filme sunt cele care apar pe site-urile respective, fara tmdb id sau tmdb id, fiecare admin de site, dupa cum si le-a aruncat acolo. Din cauza asta am preferat sa imi fac eu propriul sistem de monitorizare si am adaugat rubrica de vizionate. 
Nu se pot face sa apara bifa in celelalte, pentru ca eu nu folosesc listele tmdb ca toate celelalte addonuri.

**Comment by audiosistem** [comment]
Multumesc!Era doar un inconvenient.Bine ca inca te ocupi de el.
In alta ordine,eu mi-am modificat,dar poate pentru un ulterior :up,poti lasa linia 136 din setting sa afiseze id-ul userului.
Ma repet,multumesc! 🥇

**Comment by angelitto2005** [comment]
Ma bag si eu in discutie. Sper ca nu deranjez. Bifele trebuie sa apara si in TMDbHelper doar ca apar mai tarziu, adica dupa ce el isi face update'ul. Se poate vedea si in photo de mai jos, ca in TMDbH apar bifele la filmele vizionate recent de mine. Si asta chiar daca uneori apare mesajul de la MRSP, sau alteori nu apare. MRSP il marcheaza ca vizionat in trakt, iar TMDB, are ”datoria” sa il recunoasca  in Trakt si sa-i puna bifa cand rasfoiesti cu el librariile.
Mai refa o data autorizarile din TMDbH si MRSP si eventual verifica setarile sa nu iti fi scapat ceva. Eu am patit mai demult ca MRSP sa nu mai marcheze ca vizionat si m-am gandit sa-l autorizez din nou in Trakt. Si aia a fost buba. Dupa aceea a mers iar.

![Captură de ecran 2021-09-13 201908](https://user-images.githubusercontent.com/29383306/133128523-a3f8722c-3ad0-4546-88b0-f0fc4f8ecdac.jpg)

**Comment by audiosistem** [comment]
Ma bucur ca participi,Angellito(chiar iti folosesc playerul de MRSP in TMDB),nu te contrazic.In MRSP,la vizionate,vede tot si din externe si din MRSP,cu bife...etc.eu in linia de widget si-n TMDB nu am.L-am tot sucit si pe curat doar cu cele doua,poate-mi scapa mie ceva.Mai sap.

**Comment by audiosistem** [comment]
![1](https://user-images.githubusercontent.com/6246768/133131647-257b3292-ce30-46b8-9f0e-7332a441f626.jpg)
![2](https://user-images.githubusercontent.com/6246768/133131654-b40a4dd8-49cd-4544-90a0-77e08a55c034.jpg)
In prima e bifa la TMDB(vizualizat in alt addon),marcat.In a 2-a,pe 11 07 vazut in FSOnline(nemarcat in TMDB,dar in MRSP,marcate ambele vizionari)

**Comment by angelitto2005** [comment]
Ma bucur ca iti e de ajutor. Si eu il folosesc cateodata, dar de obicei dau direct play with MRSP caci e mai simplu
Am testat si playerul postat de tine, dar apare o caseta de dialog si asta nu-mi place. Al meu merge din prima. E mai rapid :)

Referitor la problema ta, sper ca ai bifat in setari MRSP la Misc si Trakt:
1. Adauga la Vazute si ce vizionezi din afara MRSP
2. Monitorizare Trakt si din afara MRSP.
3. Marcare automata ca vizualizat in Trakt.

Iar in TMDbH la setari ai grija la Wigets:
Hide watched  items on wigets (nu nu fie aici buba)
si la Accounts:
1. Get watched  indicators from Trakt
Astea imi vin in cap. dar bineinteles ca si in addonul Trakt tre sa fi setat bine chestiile pe acolo.

L.E. Dupa ce am vazut poza postata de tine, cred ca e buba la filmele vizionate de pe situri  online. Alea nu cred ca au mers vreodata marcate cu adevarat in Trakt si nici nu vor merge. M-as mira ca MRSP sa le marcheze ca vizionate in Trakt, caci daca  o face, atunci  TMDbH ar trebui sa preia de acolo si sa faca restul. Dar nu cred ca iti apar in Trakt ca vizionate. Si asta cred ca din cauza numelui, caci nu are IDul de TMDB, dupa care sa fie recunoscut si marcat corespunzator. Nici subtitrarile nu cred ca le cauta corect, trebuie sa dai manual. dar recunosc ca nu folosesc Filme Online (doar torrente), asa ca s-ar putea sa ma insel. 
xngsrs stie mai bine, cred cum sta treaba.

**Comment by audiosistem** [comment]
Va multumesc!Numai bine!

**Comment by xngsrs** [comment]
@angelitto2005 @audiosistem  Nu ma deranjati, nu aveti ce sa deranjati niciunul:)
Da, la asta nu m-am gandit, cum a zis angelitto2005:
  setarea cu Get watched indicators from Trakt ar trebui sa functioneze in tmdbh, dar numai daca au fost marcate in trakt. 

@audiosistem , nu am inteles cum vrei sa fac cu linia 136, dar poti sa imi scrii cum ai facut, eventual mai punem o linie :)
     De functionat bine, nu prea cred, pentru ca la ultimul update erau mai multe busite, piratebay, kickass2, fluxzone nu arata bluray ro. Mi-am dat singur seama :)
     Ca sa nu mai zic de subtitrari, ca erau busite 3 site-uri.

O sa incerc sa vad daca rezolv cumva si cu filmele online desi alea o sa dea multe rateuri din cauza numelor puse ba in romana, ba impopotanate cu alte chestii gen "subtitrat online", sau poate chiar din cauza asta nu prea merg, caz in care nu am ce sa fac.

Mai astept idei si sunt deschis la orice imbunatatire, daca inteleg ce sa fac sau daca imi spuneti cum sa fac :P

**Comment by audiosistem** [comment]
![image](https://user-images.githubusercontent.com/6246768/133142997-8aa7698b-6b97-4606-bb21-9bcba8036c7d.png)

**Comment by angelitto2005** [comment]
Ce face mai exact setarea asta?

**Comment by audiosistem** [comment]
![image](https://user-images.githubusercontent.com/6246768/133146756-b3c9f280-6698-426a-aabb-e05890f7b448.png)
Cu ea,dupa ce te autorizezi in trakt,iti apare id-ul.

**Comment by angelitto2005** [comment]
Am inteles. E foarte utila, intradevar. Sper sa fie implementata intr-un viitor update.

**Comment by audiosistem** [comment]
@angellito2005...Am** testat si playerul postat de tine, dar apare o caseta de dialog si asta nu-mi place...
Tu,folosesti mult sau doar partea de torrent,caseta ma ajuta sa vad ce site online aleg.
@xngsrs...Informatiile despre film/serial,apar doar la FilmeOnline2016.
Tine de site-uri?De cum sunt facute?
Se poate implementa,sa prea informatia,IMDB/TMDB?
Le mai folosesc in widget(FSOnline).
@xngsrs si @angelitto2005.In caz ca v-ar face placere si credeti ca mai puteti impartasi,din cunostintele voastre
https://t.me/kodiromania
Si vizual,din ce fac(cu ajutorul multora,atat cat pot),pentru comunitate https://www.youtube.com/channel/UC3BT2HmNZQc8bi8oT_JBxaQ
Va doresc,o zi minunata!

**Comment by xngsrs** [comment]
@audiosistem 

> Tine de site-uri?De cum sunt facute?

Da, tine de site-uri, la multe nu am cum sa iau informatia fara sa fac multe requesturi pe serverul lor, ceea ce incerc sa evit, pentru ca amprenta sa fie cat mai mica. Daca as face request pe fiecare film pe care il iau de pe site-uri, s-ar darama serverul respectiv destul de repede.
In principiu, nu am cum sa implementez sa preia informatia automat. Pentru asta am creat meniuri contextuale care preiau informatia la cerere, de pe imdb sau tmdb, pentru a putea vedea detaliile filmului.
Ideea mea de la inceputul MRSP a fost sa fac ceva diferit, tocmai din cauza ca toate celelalte addonuri folosesc exact aceleasi liste de filme, luate de pe tmdb. Voiam sa vad ce filme mai sunt puse online, ca sa fiu la curent, asa mai gasesc si filme de care nu stiam, dar le vad urcate pe site-uri, de streaming sau de torrenti.
Poate sa fac o "invarteala", atunci cand se opreste filmul cu mai mult de 80% vizionat si nu este recunoscut de trakt, sa bag un popup din care s-ar putea selecta exact filmul sau episodul pe care l-ai vizionat, dar nu stiu daca ar fi folosit de cineva. Nu cred ca ar fi de prea mult ajutor, ca nu stai mereu sa selectezi filmul pe care l-ai vizionat, dupa ce l-ai oprit.
Nu stiu, trebuie sa fie si cereri pentru asta :)

In legatura cu linia 136 din settings, la mine se vede userul dupa ce am autorizat, far treaba aia cu visible, de aia nu intelegeam despre ce era vorba. 
@angelitto2005  o sa o adaug in urmatorul update, ca nu ma doare mana :)

> https://t.me/kodiromania

Cu grupul pe telegram, nu stiu, am preferat toti anii astia sa raman anonim.

> Si vizual,din ce fac(cu ajutorul vostru si al multora,atat cat pot),pentru comunitate

E bine ca se mai ocupa cate cineva si de români :)
