### ISSUE TITLE
Cautarea nu functioneaza pentru FSOnline

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#55]
Salut,
Nu stiu daca si observat dar daca incerci sa cauti un titlu( exemplu: 4400) pe FSOnline, nu gaseste nimic, chiar daca serialul exista pe lista. Ar mai fi ceva. FSGratis are o singura optiune NETU, care nu functioneaza pe un Android box.
Mersi.

**Comment by xngsrs** [comment]
Salut,
Am rezolvat, pentru FSOnline, cautarea, precum si sortarea dupa ani, in [1.1.64](https://github.com/xngsrs/myhobby/commit/29736f2e21a4fd84feb878038abb20031e3dea9b)
La FSGratis, il mai las, poate isi actualizeaza lista de servere, altfel il voi scoate in curand, deoarece e inutil. NETU nu poate fi rezolvat in kodi.
