### ISSUE TITLE
Cinemagia nu functioneaza corect

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#56]
Salut,
Inca cateva lucruri care nu functioneaza. Cinemagia, dai click pe un titlu, se deschide o lusta intreaga care nu are nici o legatura cu titlul respectiv.
ClickSud si DozaAnimata nu functioneaza deloc. Addic7ed da tot timpul eroare.
Mersi.

**Comment by xngsrs** [comment]
Salut,
1. Cu Cinemagia, nu pot sa ma gandesc decat ca site-urile pe care le ai activate si se face cautarea nu gasesc niciun rezultat. Ai si un meniu contextual (clic dreapta) unde poti selecta "Cauta Variante" si poti afla asa ce text baga la cautare.
Din punctul meu de vedere, cinemagia merge exact asa cum trebuie.
2. Cand ai deschis problema, deja facusem de cateva ore un update care repara addic7ed si clicksud
Oricum, clicksud mai trebuie imbunatatit, am mai facut cate ceva azi, ramane sa rezolv cu paginarea in unele locuri.
3. Am mai lucrat putin si la dozaanimata, acolo e problema cu link-urile, nu sunt toate suportate de resolveurl.

**Comment by MisuIancu** [comment]
Mersi. Totul pare in ordine acum.

**Comment by xngsrs** [comment]
Daca e totul in regula, deocamdata, inchid prolema. 
Sper ca ma vei mai anunta de eventualele probleme peste care mai dai.
