### ISSUE TITLE
CC Google TV+Matrix+MRSP=problem?

### ISSUE THREAD

**Issue by Guguloi** [xngsrs/myhobby#57]
Salutare,

În primul rând mulțumiri pentru munca depusă, foarte utile add-on-urile tale.
În al doilea rând "problema" mea. Am MRSP instalat pe Android TV 9 și Matrix fără probleme.
În schimb pe CC Google TV și Matrix a rămas la 1.1.63 și când își făcea update la o versiune mai nouă aveam erori. 
M-a pus dreq să-l dezinstalez și să-l instalez direct la versiunea nouă 1.1.67. Nu mai vrea neam. Log-ul e ăsta: http://paste.kodi.tv/wironiyujo
Ultimele 5 erori îmi apar pe ecran la instalare.
Sigur e ceva la mine dar nu știu ce că versiunea 1.1.63 mergea brici.

Și o întrebare. E posibil să-l integrezi cu Real-Debrid? Acum folosesc Fen/Seren dar mi-ar place să folosesc MRSP cu Real-Debrid. 

Mulțumesc.

**Comment by xngsrs** [comment]
Salut,
Din log pare ca vrei sa instalezi o versiune mai veche, care functioneaza doar pe kodi <= 18.
Vad ca mai ai addonuri incompatibile cu Kodi matrix. Probabil ca cel mai bine ar fi sa resetezi complet kodi si sa il reconfigurezi, ca sa faci putina curatenie.

Da, teoretic pot sa integrez MRSP cu real-debrid, dar nu am cont si nici nu intentionez sa cumpar vreodata. Refuz sa platesc pentru asa ceva.

**Comment by Guguloi** [comment]
Da, am făcut upgrade de la 18 la 19, n-am instalat pe curat.
Ciudat e că 1.1.63 funcționa perfect.
Am încercat să instalez din repo, scria 1.1.67 acolo.

În fine, cred că trebuie s-o iau de la zero cu instalarea KODI.

Mulțumesc frumos pentru răspuns.
