### ISSUE TITLE
FSONLINE nu functioneaza 

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#58]
Salut,
Sper ca nu te deranjeaza ca te anunt cand ceva nu functioneaza. De ieri, FSONLINE nu da nici o lista cand intri pe seriale sau pe filme. Pe ClickSud, , numai serverul Ok.ru deschide emisiunea, dar se opreste constant , dupa cateva secunde. Mixdrop, Userload, Tubeload, Vidmoly, dau erori la deschidere.
Pe PortalulTauTv, numai filmele merg, pt seriale nu este nici un server.
Mersi mult pentru ceea ce faci.

**Comment by MisuIancu** [comment]
Am uitat sa-ti soun ca sunt pe Kodi 19.3 cu versiunea 1.1.71b pentru MRSP

**Comment by xngsrs** [comment]
Salut, am incercat sa reproduc problemele mentionate de catre tine:
 - La mine, fsonline merge, imi arata listele in toate meniurile, deci e posibil, daca nu esti in România, sa fie ceva blocat. Voi modifica totusi ceva in cod, ca sa imi arate si alte servere, ca lipseste nul.
 - pe clicksud, providerii de stream au schimbat ceva in cod, asteptam dupa Gujal de la ResolveUrl sa repare, daca se poate.
 - portalultautv, marea majoritate a surselor de la seriale sunt cu link-uri (netu|hqq) care nu pot fi rezolvate de ResolveUrl, deci nu vor aparea.
 
Pentru ce nu poti viziona asa, iti recomand torrentii, daca e posibil in locul unde esti tu.
Multumesc si eu, ca ai anuntat.

**Comment by MisuIancu** [comment]
Salut,
Nu cred ca e vorba de geolocalizare, site-ul oficial merge cand ies din Kodi. Cred ca se produce o eroare undeva, am sa reunstalez kodi, poate va ajuta cu ceva.
In orice caz, multumesc mult.

**Comment by MisuIancu** [comment]
Salut,
Au aparut listele acum, eu nu am mai facut nimic, probabil e datorita modificarilor pe care le ai facut.
Mersi.
