### ISSUE TITLE
plugin.video.romanianpack

### ISSUE THREAD

**Issue by tehnium** [xngsrs/myhobby#59]
scuze problema e in kodi

**Comment by xngsrs** [comment]
Sper ca ai rezolvat. Am vazut log-ul si intradevar, asa parea, ca ar fi de pe sistemul tau.

**Comment by tehnium** [comment]
Multumesc... da... era de fapt din systemul de operare debian...am verificat pe windows si nu era nici o problema....dar s-a rezolvat si pe debian... mai precis pe un dietpi cu kodi...raspberry 3 legat la un video proiector....desi am conturi si pe netflix si pe hbo.....prime... am renuntat la ele pentru ca munca ta...voastra.... este mai buna... si am mai multa incredere in gusturile si filtrul facut de baietii (si fetele ca sa nu fiu misogin) de pe site filmesubtitrate online sau filmehd decat in academia americana de film... inca odata multumesc pt munca ta !
