### ISSUE TITLE
Filme- bune ,eroare

### ISSUE THREAD

**Issue by visinel** [xngsrs/myhobby#6]
Filme-bune kodi addons nu functioneaza ,nu arata filmele doar next ,mersi mult

**Comment by visinel** [comment]
Scuze am uitat sa specific ,plugingul se afla in  movies ro site pack ,si  siteul FSOnline se afla de doua ori in pack sterge te rig unul afar ,multumes

**Comment by xngsrs** [comment]
Rezolvat filme-bune in https://github.com/xngsrs/myhobby/commit/74af19b2304a4da15951fd21e585adc9726c546f, fsonline nu este de doua ori, sunt diferite.
