### ISSUE TITLE
Eroare userload si FSONLINE 2

### ISSUE THREAD

**Issue by MisuIancu** [xngsrs/myhobby#63]
Salut, 
Nu stiu daca numai la mine, dar chisr cu versiunea 1.1.74, userload si FSOnline2 dau erori. 
Mersi si Sarbatori Fericite!

**Comment by mirelsen** [comment]
> Salut, Nu stiu daca numai la mine, dar chisr cu versiunea 1.1.74, userload si FSOnline2 dau erori. Mersi si Sarbatori Fericite!

La multi ani! Userload e momentan jos...de 1-2 zile... https://userload.co/ -->  Web server is down Error code 521

**Comment by xngsrs** [comment]
> Salut,
Nu stiu daca numai la mine, dar chisr cu versiunea 1.1.74, userload si FSOnline2 dau erori.
Mersi si Sarbatori Fericite!

Multumesc, la fel!
userload si nu numai isi mai schimba codul sau pica, ori sunt video-urile sterse de pe ele.
Nu e numai pe fsonline2, e valabil pentru toate.
Incearca alte servere pana cand va deveni celalalt functional.

> La multi ani!

La multi ani!
