### ISSUE TITLE
Subtitrări 

### ISSUE THREAD

**Issue by Guguloi** [xngsrs/myhobby#64]
Un An Nou mai bun și mulțumiri pentru munca ta.
O să dau un copy/paste la ce-am scris pe Softpedia.

Referitor la subtitrările lui sarsailă.
Am Matrix 19.3 pe TV și Maven Nexus RC2 pe CCGTV.

Regielive. Merge pe Matrix, dă eroare pe Nexus.
Subs. Merge pe ambele mai puțin arhivele rar.
Subtitrări-noi. Nu merge pe nimic.
Titrări. La fel ca subs, merge mai puțin arhivele rar.

În principiu doar subtitrări-noi folosesc că au zip-uri.

Mulțumesc.

LE. Un log la Kodi din decembrie pentru eroarea la regielive: http://paste.kodi.tv/bibisazomo

Iar referitor la subtitrări-noi practic nu mai găsește nimic nici automat nici manual și nici nu dă vreo eroare.
Am întrebat pe forumul lor referitor la add-on-ul lui sarsailă dacă au schimbat ceva la site și un admin a zis așa:
_Nu stiu despre ce add-on este vorba, dar posibil sa fie unul care are ca sursa trackerele si acestea au fost scoase de la recomandari. Daca este vorba doar de link direct subtitrari-noi.ro nu ar trebui sa fie probleme._

Alte informații nu mai am

**Comment by xngsrs** [comment]
> Un An Nou mai bun și mulțumiri pentru munca ta.
Multumesc, la fel!
In baza log-ului furnizat de tine, am facut niste update-uri, ar trebui sa fie rezolvate erorile pe nexus.
Subtitrari-noi este la versiunea 1.3.2.
Suport pentru arhivele rar, ar trebui sa ai instalat pe aparatul pe care te uiti (linux, windows), un soft de dezarhivare (rar, unrar, 7zip, ceva de genul, pe care addonul il va folosi automat)
 Pentru coreelec e de mai demult implementat pe subsro suport pentru arhivele rar cu ajutorul addonului vsf.rar (disponibil cred numai pe coreelec), ceva ce atunci am experimentat, dar neprimind niciun feedback de nicaieri, a ramas numai ala.

**Comment by Guguloi** [comment]
Mare boier, mare caracter. Respectele mele.

Totul e OK acum, merge regielive fără eroare și a înviat și subtitrări-noi.

Cît despre rar pe subs/titrări am Google TV pe Chromecast și am instalat rar suport din repository KODI dar din păcate nu vrea.
Nu e problemă mare că acum ai reparat subtitrări-noi și regielive și eu sunt happy again.

Să ai o viață frumoasă și mulțumesc.
