### ISSUE TITLE
Subs.ro. Again

### ISSUE THREAD

**Issue by Guguloi** [xngsrs/myhobby#68]
Salutare și Hristos a Înviat.

N-am mai incercat de mult să caut o subtitrare pe subs.ro dar acum sunt singurii care au subtitrare până la episodul 8 la Will Trent.
Din păcate mesajul e No subtitles found.
Am încercat și alte seriale și la fel, indiferent dacă e zip sau rar nu le găsește.
Log-ul: https://paste.kodi.tv/oduxusibok

Am zis să zic. :)

**Comment by xngsrs** [comment]
Salut și "Adevărat a Înviat!"
Scuze de întârziere, am rezolvat cu subs.ro.
Și mulțumesc pentru feedback!

**Comment by Guguloi** [comment]
Updatat. Testat. Bucurat.
Merge brici.
Mare boier, mare caracter.

Mulțumesc.
